import ResearchOS

/-!
# Generated exhaustive ledger axiom audit

Generated by `scripts/gen_axiom_audit.py` from
`data/researchos_result_registry.json`. It is deliberately excluded from `ResearchOS.lean`;
CI elaborates it standalone and validates the output with
`scripts/check_axioms.py`.
-/

#print axioms AnalyticAt.conj_conj
#print axioms Gammaℝ_conj
#print axioms ResearchOS.NumberTheory.carmichael_1105_factorization
#print axioms ResearchOS.NumberTheory.carmichael_1105_not_prime
#print axioms ResearchOS.NumberTheory.carmichael_1729_factorization
#print axioms ResearchOS.NumberTheory.carmichael_1729_not_prime
#print axioms ResearchOS.NumberTheory.carmichael_561_factorization
#print axioms ResearchOS.NumberTheory.carmichael_561_not_prime
#print axioms ResearchOS.NumberTheory.mersenne_M13_prime
#print axioms ResearchOS.NumberTheory.mersenne_M17_prime
#print axioms ResearchOS.NumberTheory.mersenne_M19_prime
#print axioms ResearchOS.NumberTheory.prime_10007
#print axioms ResearchOS.NumberTheory.prime_10009
#print axioms ResearchOS.NumberTheory.prime_2017
#print axioms analyticOnNhd_riemannXi
#print axioms analyticOnNhd_riemannZeta_strip
#print axioms analyticOrderAt_comp_const_sub
#print axioms analyticOrderAt_conj_conj
#print axioms analyticOrderAt_riemannXi_conj
#print axioms analyticOrderAt_riemannXi_eq_riemannZeta
#print axioms analyticOrderAt_riemannXi_fourfold
#print axioms analyticOrderAt_riemannXi_ne_top
#print axioms analyticOrderAt_riemannXi_one_sub
#print axioms analyticOrderAt_riemannXi_one_sub_conj
#print axioms analyticOrderAt_riemannZeta_conj
#print axioms analyticOrderAt_riemannZeta_fourfold
#print axioms analyticOrderAt_riemannZeta_ne_top_of_mem_strip
#print axioms analyticOrderAt_riemannZeta_one_sub
#print axioms analyticOrderAt_riemannZeta_one_sub_conj
#print axioms completedRiemannZeta_conj
#print axioms completedRiemannZeta₀_conj
#print axioms differentiable_riemannXi
#print axioms meromorphicOn_riemannXi
#print axioms meromorphicOn_riemannZeta_strip
#print axioms meromorphicOrderAt_riemannXi_ne_top
#print axioms meromorphicOrderAt_riemannZeta_ne_top_of_mem_strip
#print axioms one_notMem_riemannZetaZeros
#print axioms riemannHypothesis_iff_riemannXi_zeros_re_eq_half
#print axioms riemannHypothesis_iff_zero_free_gt_half
#print axioms riemannHypothesis_iff_zetaZeros_re_eq_half
#print axioms riemannHypothesis_iff_zetaZeros_re_eq_half'
#print axioms riemannXi
#print axioms riemannXi_comp_conj
#print axioms riemannXi_comp_one_sub
#print axioms riemannXi_conj
#print axioms riemannXi_divisor_apply
#print axioms riemannXi_divisor_conj
#print axioms riemannXi_divisor_nonneg
#print axioms riemannXi_divisor_one_sub
#print axioms riemannXi_divisor_one_sub_conj
#print axioms riemannXi_divisor_strip_conj
#print axioms riemannXi_divisor_strip_one_sub
#print axioms riemannXi_divisor_strip_one_sub_conj
#print axioms riemannXi_divisor_support
#print axioms riemannXi_divisor_univ_conj
#print axioms riemannXi_divisor_univ_one_sub
#print axioms riemannXi_divisor_univ_one_sub_conj
#print axioms riemannXi_eq_of_ne
#print axioms riemannXi_eq_zero_iff_riemannZeta_eq_zero
#print axioms riemannXi_ne_zero_of_one_le_re
#print axioms riemannXi_ne_zero_of_re_le_zero
#print axioms riemannXi_one
#print axioms riemannXi_one_sub
#print axioms riemannXi_zero
#print axioms riemannXi_zero_mem_critical_strip
#print axioms riemannZetaZeros_conj_image
#print axioms riemannZetaZeros_conj_preimage
#print axioms riemannZeta_comp_conj
#print axioms riemannZeta_conj
#print axioms riemannZeta_conj_eq_zero_iff
#print axioms riemannZeta_divisor_strip_apply
#print axioms riemannZeta_divisor_strip_conj
#print axioms riemannZeta_divisor_strip_nonneg
#print axioms riemannZeta_divisor_strip_one_sub
#print axioms riemannZeta_divisor_strip_one_sub_conj
#print axioms riemannZeta_divisor_strip_support
#print axioms riemannZeta_fourfold_zero
#print axioms riemannZeta_fourfold_zero'
#print axioms riemannZeta_ne_zero_of_re_eq_zero
#print axioms riemannZeta_ne_zero_of_re_le_zero
#print axioms riemannZeta_one_sub_eq_zero_iff
#print axioms riemannZeta_zero_mem_critical_strip
