import ResearchOS

/-!
# Generated exhaustive ledger axiom audit

Generated by `scripts/gen_axiom_audit.py` from
`data/researchos_result_registry.json`. It is deliberately excluded from `ResearchOS.lean`;
CI elaborates it standalone and validates the output with
`scripts/check_axioms.py`.
-/

#print axioms ResearchOS.NumberTheory.carmichael_1105_factorization
#print axioms ResearchOS.NumberTheory.carmichael_1105_not_prime
#print axioms ResearchOS.NumberTheory.carmichael_1729_factorization
#print axioms ResearchOS.NumberTheory.carmichael_1729_not_prime
#print axioms ResearchOS.NumberTheory.carmichael_561_factorization
#print axioms ResearchOS.NumberTheory.carmichael_561_not_prime
#print axioms ResearchOS.NumberTheory.mersenne_M13_prime
#print axioms ResearchOS.NumberTheory.mersenne_M17_prime
#print axioms ResearchOS.NumberTheory.mersenne_M19_prime
#print axioms ResearchOS.NumberTheory.prime_10007
#print axioms ResearchOS.NumberTheory.prime_10009
#print axioms ResearchOS.NumberTheory.prime_2017
#print axioms one_notMem_riemannZetaZeros
#print axioms riemannHypothesis_iff_zero_free_gt_half
#print axioms riemannHypothesis_iff_zetaZeros_re_eq_half
#print axioms riemannHypothesis_iff_zetaZeros_re_eq_half'
#print axioms riemannZeta_ne_zero_of_re_eq_zero
#print axioms riemannZeta_ne_zero_of_re_le_zero
#print axioms riemannZeta_one_sub_eq_zero_iff
#print axioms riemannZeta_zero_mem_critical_strip
