import ResearchOS

/-!
# Generated exhaustive ledger axiom audit

Generated by `scripts/gen_axiom_audit.py` from
`data/researchos_result_registry.json`. It is deliberately excluded from `ResearchOS.lean`;
CI elaborates it standalone and validates the output with
`scripts/check_axioms.py`.
-/

#print axioms ResearchOS.NumberTheory.carmichael_1105_factorization
#print axioms ResearchOS.NumberTheory.carmichael_1105_not_prime
#print axioms ResearchOS.NumberTheory.carmichael_1729_factorization
#print axioms ResearchOS.NumberTheory.carmichael_1729_not_prime
#print axioms ResearchOS.NumberTheory.carmichael_561_factorization
#print axioms ResearchOS.NumberTheory.carmichael_561_not_prime
#print axioms ResearchOS.NumberTheory.mersenne_M13_prime
#print axioms ResearchOS.NumberTheory.mersenne_M17_prime
#print axioms ResearchOS.NumberTheory.mersenne_M19_prime
#print axioms ResearchOS.NumberTheory.prime_10007
#print axioms ResearchOS.NumberTheory.prime_10009
#print axioms ResearchOS.NumberTheory.prime_2017
