import Mathlib

/-!
# Endpoint segment normal forms

This file proves two exact normal forms for consecutive segments. The first is
additive and the second is an ordered multiplicative transfer system. The
results apply only to the declared grammars.
-/

open scoped BigOperators

namespace Ecdlp.EndpointSegment

section Additive

variable {A : Type*} [AddCommGroup A]

/-- A constant additive defect plus a public endpoint coboundary. -/
def edgeCocycle (defect : A) (potential : ℕ → A) (index : ℕ) : A :=
  defect + potential (index + 1) - potential index

/-- Sum of consecutive edge values. -/
def segmentSum
    (defect : A) (potential : ℕ → A) (start length : ℕ) : A :=
  ∑ offset in Finset.range length,
    edgeCocycle defect potential (start + offset)

@[simp]
theorem segmentSum_zero
    (defect : A) (potential : ℕ → A) (start : ℕ) :
    segmentSum defect potential start 0 = 0 := by
  simp [segmentSum]

/-- Appending one edge extends the segment by its final edge. -/
theorem segmentSum_succ
    (defect : A) (potential : ℕ → A) (start length : ℕ) :
    segmentSum defect potential start (length + 1)
      = segmentSum defect potential start length
        + edgeCocycle defect potential (start + length) := by
  simp [segmentSum, Finset.sum_range_succ]

/-- Exact endpoint normal form for the additive grammar. -/
theorem segmentSum_normalForm
    (defect : A) (potential : ℕ → A) (start length : ℕ) :
    segmentSum defect potential start length
      = length • defect
        + potential (start + length)
        - potential start := by
  induction length with
  | zero =>
      simp [segmentSum]
  | succ length ih =>
      rw [segmentSum_succ, ih]
      simp [edgeCocycle, Nat.succ_eq_add_one, add_nsmul, Nat.add_assoc] <;>
        abel

/-- Exact binary composition of adjacent segments. -/
theorem segmentSum_add
    (defect : A) (potential : ℕ → A)
    (start leftLength rightLength : ℕ) :
    segmentSum defect potential start (leftLength + rightLength)
      = segmentSum defect potential start leftLength
        + segmentSum defect potential (start + leftLength) rightLength := by
  simp only [segmentSum_normalForm]
  simp [add_nsmul, Nat.add_assoc] <;> abel

/-- Remove the endpoint contribution from a segment. -/
def endpointResidual
    (defect : A) (potential : ℕ → A) (start length : ℕ) : A :=
  segmentSum defect potential start length
    - (potential (start + length) - potential start)

/-- The residual is exactly the length character generated by the defect. -/
theorem endpointResidual_eq_length_smul
    (defect : A) (potential : ℕ → A) (start length : ℕ) :
    endpointResidual defect potential start length = length • defect := by
  unfold endpointResidual
  rw [segmentSum_normalForm]
  abel

/-- Residuals compose by addition of segment lengths. -/
theorem endpointResidual_add
    (defect : A) (potential : ℕ → A)
    (start leftLength rightLength : ℕ) :
    endpointResidual defect potential start (leftLength + rightLength)
      = endpointResidual defect potential start leftLength
        + endpointResidual defect potential (start + leftLength) rightLength := by
  simp [endpointResidual_eq_length_smul, add_nsmul]

/-- Binary specialization of the residual. -/
theorem endpointResidual_zmodTwo
    (potential : ℕ → ZMod 2) (start length : ℕ) :
    endpointResidual (1 : ZMod 2) potential start length
      = (length : ZMod 2) := by
  simp [endpointResidual_eq_length_smul]

/-- A decoder that sees only endpoint values and works uniformly for every
potential and length forces the constant defect to vanish. -/
theorem endpointOnly_decoder_forces_trivial_defect
    (defect : A)
    (decode : A → A → A)
    (hdecode :
      ∀ (potential : ℕ → A) (start length : ℕ),
        decode (potential start) (potential (start + length))
          = segmentSum defect potential start length) :
    defect = 0 := by
  let potential : ℕ → A := fun _ => 0
  have hzero := hdecode potential 0 0
  have hone := hdecode potential 0 1
  simp [segmentSum, edgeCocycle, potential] at hzero hone
  exact hone.symm.trans hzero

/-- No uniform endpoint-only decoder exists for a nonzero defect in this
additive grammar. -/
theorem no_endpointOnly_decoder_of_nontrivial_defect
    (defect : A) (hdefect : defect ≠ 0) :
    ¬ ∃ decode : A → A → A,
      ∀ (potential : ℕ → A) (start length : ℕ),
        decode (potential start) (potential (start + length))
          = segmentSum defect potential start length := by
  rintro ⟨decode, hdecode⟩
  exact hdefect
    (endpointOnly_decoder_forces_trivial_defect defect decode hdecode)

end Additive

section Transfer

variable {M : Type*} [Group M]

/-- A transition obtained by gauging one constant group element. -/
def gaugeTransition
    (constant : M) (gauge : ℕ → M) (index : ℕ) : M :=
  gauge (index + 1) * constant * (gauge index)⁻¹

/-- Ordered product of consecutive transitions. Later transitions multiply on
the left. -/
def transferSegment
    (constant : M) (gauge : ℕ → M) (start : ℕ) : ℕ → M
  | 0 => 1
  | length + 1 =>
      gaugeTransition constant gauge (start + length)
        * transferSegment constant gauge start length

@[simp]
theorem transferSegment_zero
    (constant : M) (gauge : ℕ → M) (start : ℕ) :
    transferSegment constant gauge start 0 = 1 := rfl

@[simp]
theorem transferSegment_succ
    (constant : M) (gauge : ℕ → M) (start length : ℕ) :
    transferSegment constant gauge start (length + 1)
      = gaugeTransition constant gauge (start + length)
        * transferSegment constant gauge start length := rfl

/-- Exact endpoint normal form for the transfer grammar. -/
theorem transferSegment_normalForm
    (constant : M) (gauge : ℕ → M) (start length : ℕ) :
    transferSegment constant gauge start length
      = gauge (start + length)
        * constant ^ length
        * (gauge start)⁻¹ := by
  induction length with
  | zero =>
      simp [transferSegment]
  | succ length ih =>
      rw [transferSegment_succ, ih]
      simp [gaugeTransition, pow_succ', Nat.add_assoc, mul_assoc]

/-- Removing the endpoint gauges leaves the constant transition raised to the
segment length. -/
theorem transferEndpointResidual_eq_power
    (constant : M) (gauge : ℕ → M) (start length : ℕ) :
    (gauge (start + length))⁻¹
        * transferSegment constant gauge start length
        * gauge start
      = constant ^ length := by
  rw [transferSegment_normalForm]
  group

/-- Exact ordered binary composition of adjacent transfer segments. -/
theorem transferSegment_add
    (constant : M) (gauge : ℕ → M)
    (start leftLength rightLength : ℕ) :
    transferSegment constant gauge start (leftLength + rightLength)
      = transferSegment constant gauge (start + leftLength) rightLength
        * transferSegment constant gauge start leftLength := by
  simp only [transferSegment_normalForm]
  have hp :
      constant ^ (leftLength + rightLength)
        = constant ^ rightLength * constant ^ leftLength := by
    rw [Nat.add_comm, pow_add]
  rw [hp]
  simp [Nat.add_assoc, mul_assoc]

/-- A decoder that sees only endpoint gauges and works uniformly for every
length forces the constant transition to be the identity. -/
theorem transferEndpointOnly_decoder_forces_constant_one
    (constant : M)
    (decode : M → M → M)
    (hdecode :
      ∀ (gauge : ℕ → M) (start length : ℕ),
        decode (gauge start) (gauge (start + length))
          = transferSegment constant gauge start length) :
    constant = 1 := by
  let gauge : ℕ → M := fun _ => 1
  have hzero := hdecode gauge 0 0
  have hone := hdecode gauge 0 1
  simp [transferSegment, gaugeTransition, gauge] at hzero hone
  exact hone.symm.trans hzero

/-- No uniform endpoint-gauge-only decoder exists for a nonidentity constant
transition in this transfer grammar. -/
theorem no_transferEndpointOnly_decoder_of_nontrivial_constant
    (constant : M) (hconstant : constant ≠ 1) :
    ¬ ∃ decode : M → M → M,
      ∀ (gauge : ℕ → M) (start length : ℕ),
        decode (gauge start) (gauge (start + length))
          = transferSegment constant gauge start length := by
  rintro ⟨decode, hdecode⟩
  exact hconstant
    (transferEndpointOnly_decoder_forces_constant_one
      constant decode hdecode)

end Transfer

end Ecdlp.EndpointSegment
