import Mathlib
import Ecdlp.Proved.FunctionFieldEval

/-!
# Weil rung W3 (presentation extraction): every function-field element is a quotient `a/b`

`FunctionFieldEval` built the evaluation calculus for *presented* fractions `a/b` of regular
functions (`evalFracAt`), and its docstring named the missing piece: proving that every element of
the abstract function field `F(E) = Frac F[E]` — in particular the W2 Miller function `f_P`, which
rung W2 produces only as an abstract generator — actually **admits** such a presentation. This
file lands that extraction. Mathlib's `FunctionField` is literally `FractionRing F[E]` (the
localization of the coordinate ring at its nonzerodivisors), so the fraction-ring API applies:

* `algebraMap_functionField_ne_zero` — the coordinate ring embeds in its function field: a nonzero
  regular function stays nonzero as a rational function (injectivity of `algebraMap`);
* `functionField_exists_mul_num_den` — **extraction, multiplicative form**: every `f ∈ F(E)` has
  regular `a, b ∈ F[E]` with `b ≠ 0` and `f * (algebraMap b) = algebraMap a`. Division-free, the
  witness shape the evaluation layers consume (`evalRatAt_eq_evalFracAt` uses exactly this form);
* `functionField_exists_num_den` — **extraction, quotient form**: `f = algebraMap a / algebraMap b`
  with `b ≠ 0` — the headline `a/b`-presentation, using the field structure of `F(E)`;
* `functionField_num_den_mul` — the quotient form converts back to the multiplicative form, so the
  two presentations are interchangeable;
* `functionField_num_den_cross` — **faithfulness**: two presentations of the same `f`
  cross-multiply in the coordinate ring, `a₁ * b₂ = a₂ * b₁` — the bridge from abstract equality
  in `F(E)` to the hypothesis of `evalFracAt_well_defined`;
* `functionField_num_ne_zero` — a presentation of a nonzero `f` has nonzero numerator;
* `evalFracAt_num_den_well_defined` — **evaluation of an abstract element via presentations is
  well-posed**: any two presentations of the same `f` whose denominators are nonzero at `P` give
  the same `evalFracAt` value. Pure reuse of `evalFracAt_well_defined` through the cross lemma;
* `secp256k1_miller_function_num_den` — **the Miller connection**: the W2 Miller function `f` (any
  generator of `(XYIdeal' h)ⁿ`) equals `algebraMap a / algebraMap b` with `b ≠ 0`, and the
  fractional ideal `(XYIdeal' h)ⁿ` is generated by that explicit quotient. Miller's abstract
  generator now has the concrete numerator/denominator shape that `evalFracAt` evaluates.

**Honest scope.** The extraction gives *some* presentation with `b ≠ 0`; it gives **no control on
where `b` vanishes**. Choosing a presentation whose denominator is nonzero at a *given* point `P`
where `f` is regular (welding this file to `evalRatAt` on the local ring at `P`) is the next rung,
as are evaluation at whole divisors `f_P(D_Q)` and Weil reciprocity (W4, `notes/FOUNDATIONS.md`).
Curve-agnostic except the final secp256k1 theorem. No new axioms; fully kernel-checked.
-/

namespace Ecdlp.Weil

open Polynomial WeierstrassCurve.Affine WeierstrassCurve.Affine.CoordinateRing

variable {F : Type*} [Field F] {W : WeierstrassCurve.Affine F}

/-- **The coordinate ring embeds in the function field.** A nonzero regular function is nonzero as
a rational function: `algebraMap F[E] F(E)` is injective (the fraction-ring localization map), so
it reflects `≠ 0`. This is what lets nonvanishing hypotheses transport between the presentation
layer (`F[E]`) and the abstract layer (`F(E)`). -/
theorem algebraMap_functionField_ne_zero {r : W.CoordinateRing} (hr : r ≠ 0) :
    algebraMap W.CoordinateRing W.FunctionField r ≠ 0 := fun h0 =>
  hr (IsFractionRing.injective W.CoordinateRing W.FunctionField
    (h0.trans (map_zero (algebraMap W.CoordinateRing W.FunctionField)).symm))

/-- **Presentation extraction, multiplicative form.** Every element `f` of the function field
`F(E) = Frac F[E]` admits regular functions `a, b ∈ F[E]` with `b ≠ 0` and
`f * (algebraMap b) = algebraMap a` — the division-free witness that `f = a/b`. This is the
defining surjectivity of the fraction-ring localization (`IsLocalization.surj` at the submonoid of
nonzerodivisors), specialized to the curve's function field; the nonzerodivisor witness for `b`
becomes `b ≠ 0` because the coordinate ring of a Weierstrass curve over a field is a domain. -/
theorem functionField_exists_mul_num_den (f : W.FunctionField) :
    ∃ a b : W.CoordinateRing, b ≠ 0 ∧
      f * algebraMap W.CoordinateRing W.FunctionField b
        = algebraMap W.CoordinateRing W.FunctionField a := by
  obtain ⟨⟨a, b⟩, hab⟩ := IsLocalization.surj (nonZeroDivisors W.CoordinateRing) f
  exact ⟨a, (b : W.CoordinateRing), nonZeroDivisors.ne_zero b.2, hab⟩

/-- **Presentation extraction, quotient form (the `a/b` presentation).** Every element of the
function field is a genuine quotient of regular functions: `f = algebraMap a / algebraMap b` with
`b ≠ 0`. Division happens in the field `F(E)`; the denominator is nonzero there by
`algebraMap_functionField_ne_zero`. This is the missing hypothesis-shape named by
`FunctionFieldEval`: the abstract Miller function can now be handed to the presented-fraction
calculus. -/
theorem functionField_exists_num_den (f : W.FunctionField) :
    ∃ a b : W.CoordinateRing, b ≠ 0 ∧
      f = algebraMap W.CoordinateRing W.FunctionField a
        / algebraMap W.CoordinateRing W.FunctionField b := by
  obtain ⟨a, b, hb, hab⟩ := functionField_exists_mul_num_den f
  exact ⟨a, b, hb, (eq_div_iff (algebraMap_functionField_ne_zero hb)).mpr hab⟩

/-- The quotient form of a presentation converts back to the multiplicative form: from
`f = algebraMap a / algebraMap b` with `b ≠ 0` one recovers `f * (algebraMap b) = algebraMap a`.
Together with `functionField_exists_num_den` this makes the two presentation shapes
interchangeable, so downstream lemmas may consume whichever is convenient. -/
theorem functionField_num_den_mul {f : W.FunctionField} {a b : W.CoordinateRing} (hb : b ≠ 0)
    (hab : f = algebraMap W.CoordinateRing W.FunctionField a
        / algebraMap W.CoordinateRing W.FunctionField b) :
    f * algebraMap W.CoordinateRing W.FunctionField b
      = algebraMap W.CoordinateRing W.FunctionField a :=
  (eq_div_iff (algebraMap_functionField_ne_zero hb)).mp hab

/-- **Faithfulness: two presentations of the same element cross-multiply in the coordinate
ring.** If `f * (algebraMap b₁) = algebraMap a₁` and `f * (algebraMap b₂) = algebraMap a₂`, then
`a₁ * b₂ = a₂ * b₁` in `F[E]`. Equality of abstract fractions descends to the cross-multiplication
identity on numerators and denominators — exactly the hypothesis of `evalFracAt_well_defined` —
via injectivity of `algebraMap F[E] F(E)`. No nonvanishing hypotheses are needed. -/
theorem functionField_num_den_cross {f : W.FunctionField} {a₁ b₁ a₂ b₂ : W.CoordinateRing}
    (h₁ : f * algebraMap W.CoordinateRing W.FunctionField b₁
        = algebraMap W.CoordinateRing W.FunctionField a₁)
    (h₂ : f * algebraMap W.CoordinateRing W.FunctionField b₂
        = algebraMap W.CoordinateRing W.FunctionField a₂) :
    a₁ * b₂ = a₂ * b₁ := by
  apply IsFractionRing.injective W.CoordinateRing W.FunctionField
  rw [map_mul, map_mul, ← h₁, ← h₂]
  ring

/-- A presentation of a **nonzero** element has nonzero numerator: if `f ≠ 0` and
`f * (algebraMap b) = algebraMap a` with `b ≠ 0`, then `a ≠ 0`. The function field is a field, so
the product of the nonzero `f` with the nonzero image of `b` cannot be zero. -/
theorem functionField_num_ne_zero {f : W.FunctionField} (hf : f ≠ 0)
    {a b : W.CoordinateRing} (hb : b ≠ 0)
    (hab : f * algebraMap W.CoordinateRing W.FunctionField b
        = algebraMap W.CoordinateRing W.FunctionField a) :
    a ≠ 0 := by
  rintro rfl
  rw [map_zero] at hab
  exact mul_ne_zero hf (algebraMap_functionField_ne_zero hb) hab

/-- **Evaluating an abstract function-field element via presentations is well-posed.** If `a₁/b₁`
and `a₂/b₂` both present the same `f ∈ F(E)` (multiplicative witnesses) and both denominators are
nonzero at the rational point `P`, the presented values agree:
`evalFracAt h a₁ b₁ = evalFracAt h a₂ b₂`. So "the value of `f` at `P` through any regular
presentation" depends only on `f`, not on the extracted pair — the presentation produced by
`functionField_exists_mul_num_den` is as good as any other. Pure reuse: the cross lemma feeds
`evalFracAt_well_defined`. -/
theorem evalFracAt_num_den_well_defined {x y : F} (h : W.Equation x y)
    {f : W.FunctionField} {a₁ b₁ a₂ b₂ : W.CoordinateRing}
    (h₁ : f * algebraMap W.CoordinateRing W.FunctionField b₁
        = algebraMap W.CoordinateRing W.FunctionField a₁)
    (h₂ : f * algebraMap W.CoordinateRing W.FunctionField b₂
        = algebraMap W.CoordinateRing W.FunctionField a₂)
    (hb₁ : evalAt h b₁ ≠ 0) (hb₂ : evalAt h b₂ ≠ 0) :
    evalFracAt h a₁ b₁ = evalFracAt h a₂ b₂ :=
  evalFracAt_well_defined h (functionField_num_den_cross h₁ h₂) hb₁ hb₂

section Secp256k1

variable [Fact (Nat.Prime Secp256k1.p)]

/-- **The Miller function of secp256k1 in numerator/denominator form.** If `f` is a Miller
function for the torsion data `(P, n)` — a generator of the fractional ideal `(XYIdeal' h)ⁿ`, as
produced abstractly by rung W2 (`secp256k1_miller_function_exists`) — then `f` is an explicit
quotient of regular functions: there are `a, b ∈ F[secp256k1]` with `b ≠ 0`,
`f = algebraMap a / algebraMap b`, **and** the fractional ideal `(XYIdeal' h)ⁿ` is generated by
that concrete quotient. The abstract W2 generator thereby enters the presented-fraction evaluation
calculus of `FunctionFieldEval` (`evalFracAt`, `evalFracAt_num_den_well_defined`); by rung 3
(`secp256k1_miller_function_unique` + `secp256k1_miller_eval_scaling`) changing the Miller
representative only rescales presented values by a globally nonvanishing unit value. -/
theorem secp256k1_miller_function_num_den
    {x y : ZMod Secp256k1.p} (h : Ecdlp.Curve.secp256k1.toAffine.Nonsingular x y) (n : ℕ)
    (f : Ecdlp.Curve.secp256k1.toAffine.FunctionField)
    (hf : (↑(CoordinateRing.XYIdeal' h ^ n) :
        Submodule Ecdlp.Curve.secp256k1.toAffine.CoordinateRing
          Ecdlp.Curve.secp256k1.toAffine.FunctionField)
        = Submodule.span Ecdlp.Curve.secp256k1.toAffine.CoordinateRing {f}) :
    ∃ a b : Ecdlp.Curve.secp256k1.toAffine.CoordinateRing, b ≠ 0 ∧
      f = algebraMap Ecdlp.Curve.secp256k1.toAffine.CoordinateRing
            Ecdlp.Curve.secp256k1.toAffine.FunctionField a
        / algebraMap Ecdlp.Curve.secp256k1.toAffine.CoordinateRing
            Ecdlp.Curve.secp256k1.toAffine.FunctionField b ∧
      (↑(CoordinateRing.XYIdeal' h ^ n) :
          Submodule Ecdlp.Curve.secp256k1.toAffine.CoordinateRing
            Ecdlp.Curve.secp256k1.toAffine.FunctionField)
        = Submodule.span Ecdlp.Curve.secp256k1.toAffine.CoordinateRing
            {algebraMap Ecdlp.Curve.secp256k1.toAffine.CoordinateRing
                Ecdlp.Curve.secp256k1.toAffine.FunctionField a
              / algebraMap Ecdlp.Curve.secp256k1.toAffine.CoordinateRing
                Ecdlp.Curve.secp256k1.toAffine.FunctionField b} := by
  obtain ⟨a, b, hb, hab⟩ := functionField_exists_num_den f
  exact ⟨a, b, hb, hab, by rw [hf, hab]⟩

end Secp256k1

end Ecdlp.Weil
