import Mathlib

/-!
# Generator-orientation blindness

The public subgroup generated by `G` is unchanged when the generator is
replaced by `-G`, while a generator-relative carry or parity target is
complemented.  Consequently a decoder that is blind to the choice between
`G` and `-G` cannot be correct for both generators.

This file formalizes only the abstract logical obstruction and the elementary
set covariance under a change of indexing equivalence.  It does not formalize
elliptic curves, CM isogenies, half-kernel polynomials, theta groups, or an
ECDLP lower bound.
-/

namespace Ecdlp.ParityLift

/-- Reindex a point predicate after changing the chosen generator by an
equivalence.  In the cyclic-group application, `u` is multiplication by the
new generator multiplier. -/
def reorientedSet
    {A : Type*}
    (positive : Set A)
    (u : A ≃ A) : Set A :=
  {q | u.symm q ∈ positive}

/-- The reoriented positive set is exactly the image of the old positive set. -/
theorem reorientedSet_eq_image
    {A : Type*}
    (positive : Set A)
    (u : A ≃ A) :
    reorientedSet positive u = u '' positive := by
  ext q
  constructor
  · intro hq
    change u.symm q ∈ positive at hq
    exact ⟨u.symm q, hq, u.apply_symm_apply q⟩
  · rintro ⟨p, hp, rfl⟩
    change u.symm (u p) ∈ positive
    simpa using hp

/-- A decoder whose output is unchanged by `G -> -G` cannot equal a target
which is complemented by the same generator change. -/
theorem generatorBlind_cannot_decode_complementaryTargets
    {Γ : Type*} [Neg Γ]
    (decode target : Γ → Γ → Bool)
    (G Q : Γ)
    (hblind : decode G Q = decode (-G) Q)
    (hflip : target (-G) Q = !(target G Q))
    (hcorrectG : decode G Q = target G Q)
    (hcorrectNeg : decode (-G) Q = target (-G) Q) :
    False := by
  have h : target G Q = !(target G Q) := by
    calc
      target G Q = decode G Q := hcorrectG.symm
      _ = decode (-G) Q := hblind
      _ = target (-G) Q := hcorrectNeg
      _ = !(target G Q) := hflip
  cases htarget : target G Q <;> simp [htarget] at h

/-- Equivalent contrapositive form: if a decoder is correct for both
complementary generator-relative targets, then it must distinguish `G` from
`-G` on that query. -/
theorem correctComplementaryTargets_force_generatorSensitivity
    {Γ : Type*} [Neg Γ]
    (decode target : Γ → Γ → Bool)
    (G Q : Γ)
    (hflip : target (-G) Q = !(target G Q))
    (hcorrectG : decode G Q = target G Q)
    (hcorrectNeg : decode (-G) Q = target (-G) Q) :
    decode G Q ≠ decode (-G) Q := by
  intro hblind
  exact generatorBlind_cannot_decode_complementaryTargets
    decode target G Q hblind hflip hcorrectG hcorrectNeg

end Ecdlp.ParityLift
