import Mathlib
import Ecdlp.Proved.P256Curve

/-! # Machine-checked primality of NIST P-256 `p` (Pratt certificate, generated by `scripts/pratt_certificate.py`). Witness a=6, 9 recursive nodes. -/

namespace Ecdlp.P256.Primality
open Nat

theorem pr_6700417 : Nat.Prime 6700417 := by
  refine lucas_primality 6700417 (5 : ZMod 6700417) (by native_decide) ?_
  intro q hq hqd
  rw [show (6700417 : ℕ) - 1 = 2 ^ 7 * (3 ^ 1 * (17449 ^ 1)) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 17449 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_66417393611 : Nat.Prime 66417393611 := by
  refine lucas_primality 66417393611 (6 : ZMod 66417393611) (by native_decide) ?_
  intro q hq hqd
  rw [show (66417393611 : ℕ) - 1 = 2 ^ 1 * (5 ^ 1 * (53 ^ 1 * (173 ^ 1 * (197 ^ 1 * (3677 ^ 1))))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 53 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 173 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 197 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
          ·
            rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3677 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_11290956913871 : Nat.Prime 11290956913871 := by
  refine lucas_primality 11290956913871 (13 : ZMod 11290956913871) (by native_decide) ?_
  intro q hq hqd
  rw [show (11290956913871 : ℕ) - 1 = 2 ^ 1 * (5 ^ 1 * (17 ^ 1 * (66417393611 ^ 1))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 17 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rw [(Nat.prime_dvd_prime_iff_eq hq pr_66417393611).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_204061199 : Nat.Prime 204061199 := by
  refine lucas_primality 204061199 (11 : ZMod 204061199) (by native_decide) ?_
  intro q hq hqd
  rw [show (204061199 : ℕ) - 1 = 2 ^ 1 * (11 ^ 1 * (23 ^ 1 * (107 ^ 1 * (3769 ^ 1)))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 11 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 23 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 107 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3769 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_34282281433 : Nat.Prime 34282281433 := by
  refine lucas_primality 34282281433 (17 : ZMod 34282281433) (by native_decide) ?_
  intro q hq hqd
  rw [show (34282281433 : ℕ) - 1 = 2 ^ 3 * (3 ^ 1 * (7 ^ 1 * (204061199 ^ 1))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 7 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rw [(Nat.prime_dvd_prime_iff_eq hq pr_204061199).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_46076956964474543 : Nat.Prime 46076956964474543 := by
  refine lucas_primality 46076956964474543 (5 : ZMod 46076956964474543) (by native_decide) ?_
  intro q hq hqd
  rw [show (46076956964474543 : ℕ) - 1 = 2 ^ 1 * (23 ^ 1 * (18169 ^ 1 * (704251 ^ 1 * (78283 ^ 1)))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 23 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 18169 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 704251 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 78283 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_774023187263532362759620327192479577272145303 : Nat.Prime 774023187263532362759620327192479577272145303 := by
  refine lucas_primality 774023187263532362759620327192479577272145303 (3 : ZMod 774023187263532362759620327192479577272145303) (by native_decide) ?_
  intro q hq hqd
  rw [show (774023187263532362759620327192479577272145303 : ℕ) - 1 = 2 ^ 1 * (3 ^ 2 * (2411 ^ 1 * (11290956913871 ^ 1 * (34282281433 ^ 1 * (46076956964474543 ^ 1))))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2411 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq pr_11290956913871).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq pr_34282281433).mp (hq.dvd_of_dvd_pow h)]; native_decide
          ·
            rw [(Nat.prime_dvd_prime_iff_eq hq pr_46076956964474543).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_835945042244614951780389953367877943453916927241 : Nat.Prime 835945042244614951780389953367877943453916927241 := by
  refine lucas_primality 835945042244614951780389953367877943453916927241 (11 : ZMod 835945042244614951780389953367877943453916927241) (by native_decide) ?_
  intro q hq hqd
  rw [show (835945042244614951780389953367877943453916927241 : ℕ) - 1 = 2 ^ 3 * (3 ^ 3 * (5 ^ 1 * (774023187263532362759620327192479577272145303 ^ 1))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rw [(Nat.prime_dvd_prime_iff_eq hq pr_774023187263532362759620327192479577272145303).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_115792089210356248762697446949407573530086143415290314195533631308867097853951 : Nat.Prime 115792089210356248762697446949407573530086143415290314195533631308867097853951 := by
  refine lucas_primality 115792089210356248762697446949407573530086143415290314195533631308867097853951 (6 : ZMod 115792089210356248762697446949407573530086143415290314195533631308867097853951) (by native_decide) ?_
  intro q hq hqd
  rw [show (115792089210356248762697446949407573530086143415290314195533631308867097853951 : ℕ) - 1 = 2 ^ 1 * (3 ^ 1 * (5 ^ 2 * (17 ^ 1 * (257 ^ 1 * (641 ^ 1 * (1531 ^ 1 * (65537 ^ 1 * (490463 ^ 1 * (6700417 ^ 1 * (835945042244614951780389953367877943453916927241 ^ 1)))))))))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 17 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 257 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
          ·
            rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 641 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
            ·
              rcases (Nat.Prime.dvd_mul hq).mp h with h | h
              · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 1531 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
              ·
                rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 65537 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
                ·
                  rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 490463 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
                  ·
                    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                    · rw [(Nat.prime_dvd_prime_iff_eq hq pr_6700417).mp (hq.dvd_of_dvd_pow h)]; native_decide
                    ·
                      rw [(Nat.prime_dvd_prime_iff_eq hq pr_835945042244614951780389953367877943453916927241).mp (hq.dvd_of_dvd_pow h)]; native_decide

/-- NIST P-256 p is prime (full Pratt certificate). -/
theorem p256_p_prime : Nat.Prime Ecdlp.P256.p := pr_115792089210356248762697446949407573530086143415290314195533631308867097853951

instance : Fact (Nat.Prime Ecdlp.P256.p) := ⟨p256_p_prime⟩

end Ecdlp.P256.Primality

