import Mathlib
import Ecdlp.Proved.P256Curve

/-! # Machine-checked primality of NIST P-256 `n` (Pratt certificate, generated by `scripts/pratt_certificate.py`). Witness a=7, 10 recursive nodes. -/

namespace Ecdlp.P256.Primality
open Nat

theorem pr_3969899 : Nat.Prime 3969899 := by
  refine lucas_primality 3969899 (2 : ZMod 3969899) (by native_decide) ?_
  intro q hq hqd
  rw [show (3969899 : ℕ) - 1 = 2 ^ 1 * (19 ^ 1 * (104471 ^ 1)) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 19 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 104471 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_1002328039319 : Nat.Prime 1002328039319 := by
  refine lucas_primality 1002328039319 (19 : ZMod 1002328039319) (by native_decide) ?_
  intro q hq hqd
  rw [show (1002328039319 : ℕ) - 1 = 2 ^ 1 * (126241 ^ 1 * (3969899 ^ 1)) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 126241 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rw [(Nat.prime_dvd_prime_iff_eq hq pr_3969899).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_9350987 : Nat.Prime 9350987 := by
  refine lucas_primality 9350987 (2 : ZMod 9350987) (by native_decide) ?_
  intro q hq hqd
  rw [show (9350987 : ℕ) - 1 = 2 ^ 1 * (17 ^ 1 * (229 ^ 1 * (1201 ^ 1))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 17 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 229 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 1201 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_187019741 : Nat.Prime 187019741 := by
  refine lucas_primality 187019741 (2 : ZMod 187019741) (by native_decide) ?_
  intro q hq hqd
  rw [show (187019741 : ℕ) - 1 = 2 ^ 2 * (5 ^ 1 * (9350987 ^ 1)) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rw [(Nat.prime_dvd_prime_iff_eq hq pr_9350987).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_311245691 : Nat.Prime 311245691 := by
  refine lucas_primality 311245691 (2 : ZMod 311245691) (by native_decide) ?_
  intro q hq hqd
  rw [show (311245691 : ℕ) - 1 = 2 ^ 1 * (5 ^ 1 * (7 ^ 1 * (17 ^ 1 * (29 ^ 2 * (311 ^ 1))))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 7 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 17 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 29 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
          ·
            rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 311 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_622491383 : Nat.Prime 622491383 := by
  refine lucas_primality 622491383 (5 : ZMod 622491383) (by native_decide) ?_
  intro q hq hqd
  rw [show (622491383 : ℕ) - 1 = 2 ^ 1 * (311245691 ^ 1) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rw [(Nat.prime_dvd_prime_iff_eq hq pr_311245691).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_191039911 : Nat.Prime 191039911 := by
  refine lucas_primality 191039911 (3 : ZMod 191039911) (by native_decide) ?_
  intro q hq hqd
  rw [show (191039911 : ℕ) - 1 = 2 ^ 1 * (3 ^ 1 * (5 ^ 1 * (41 ^ 1 * (155317 ^ 1)))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 41 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 155317 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_208150935158385979 : Nat.Prime 208150935158385979 := by
  refine lucas_primality 208150935158385979 (2 : ZMod 208150935158385979) (by native_decide) ?_
  intro q hq hqd
  rw [show (208150935158385979 : ℕ) - 1 = 2 ^ 1 * (3 ^ 1 * (11 ^ 1 * (43 ^ 1 * (127 ^ 1 * (3023 ^ 1 * (191039911 ^ 1)))))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 11 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 43 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 127 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
          ·
            rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3023 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
            ·
              rw [(Nat.prime_dvd_prime_iff_eq hq pr_191039911).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_2624747550333869278416773953 : Nat.Prime 2624747550333869278416773953 := by
  refine lucas_primality 2624747550333869278416773953 (7 : ZMod 2624747550333869278416773953) (by native_decide) ?_
  intro q hq hqd
  rw [show (2624747550333869278416773953 : ℕ) - 1 = 2 ^ 6 * (3 ^ 2 * (1297 ^ 1 * (16879 ^ 1 * (208150935158385979 ^ 1)))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 1297 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 16879 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rw [(Nat.prime_dvd_prime_iff_eq hq pr_208150935158385979).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_115792089210356248762697446949407573529996955224135760342422259061068512044369 : Nat.Prime 115792089210356248762697446949407573529996955224135760342422259061068512044369 := by
  refine lucas_primality 115792089210356248762697446949407573529996955224135760342422259061068512044369 (7 : ZMod 115792089210356248762697446949407573529996955224135760342422259061068512044369) (by native_decide) ?_
  intro q hq hqd
  rw [show (115792089210356248762697446949407573529996955224135760342422259061068512044369 : ℕ) - 1 = 2 ^ 4 * (3 ^ 1 * (71 ^ 1 * (131 ^ 1 * (373 ^ 1 * (3407 ^ 1 * (17449 ^ 1 * (38189 ^ 1 * (1002328039319 ^ 1 * (187019741 ^ 1 * (622491383 ^ 1 * (2624747550333869278416773953 ^ 1))))))))))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 71 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 131 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 373 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
          ·
            rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3407 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
            ·
              rcases (Nat.Prime.dvd_mul hq).mp h with h | h
              · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 17449 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
              ·
                rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 38189 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
                ·
                  rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                  · rw [(Nat.prime_dvd_prime_iff_eq hq pr_1002328039319).mp (hq.dvd_of_dvd_pow h)]; native_decide
                  ·
                    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                    · rw [(Nat.prime_dvd_prime_iff_eq hq pr_187019741).mp (hq.dvd_of_dvd_pow h)]; native_decide
                    ·
                      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                      · rw [(Nat.prime_dvd_prime_iff_eq hq pr_622491383).mp (hq.dvd_of_dvd_pow h)]; native_decide
                      ·
                        rw [(Nat.prime_dvd_prime_iff_eq hq pr_2624747550333869278416773953).mp (hq.dvd_of_dvd_pow h)]; native_decide

/-- NIST P-256 n is prime (full Pratt certificate). -/
theorem p256_n_prime : Nat.Prime Ecdlp.P256.n := pr_115792089210356248762697446949407573529996955224135760342422259061068512044369

instance : Fact (Nat.Prime Ecdlp.P256.n) := ⟨p256_n_prime⟩

end Ecdlp.P256.Primality

