import Ecdlp.Proved.GeneratorOrder
import Ecdlp.Proved.Torsion
import Ecdlp.Proved.DlogCompleteness

/-!
# Protocol correctness on the **concrete** secp256k1 subgroup `⟨G⟩`

`DlogCompleteness.lean` proves the correctness of the deployed discrete-log protocols
(Schnorr, Diffie–Hellman, Taproot, MuSig, threshold/Feldman/ElGamal, adaptor signatures)
*abstractly*, over any `ZMod n`-module `G`. That abstraction is honest but it leaves a
gap: nothing there says the abstract carrier is realised by a real elliptic-curve group.

This file closes that gap for secp256k1. It instantiates the protocol algebra on the
**concrete** cyclic subgroup `⟨G⟩ = zmultiples secp256k1G` — the actual prime-order-`n`
group Bitcoin/Ethereum cryptography operates in — and re-derives every protocol-correctness
statement there, about genuine `WeierstrassCurve.Affine.Point` values of the secp256k1 curve.

The bridge that makes this possible is new connective tissue, not available from Mathlib:

* `secp256k1_grp_nsmul_eq_zero` — every point of `⟨G⟩` is killed by `n`. This uses the
  weak point-counting keystone `addOrderOf secp256k1G = n` (`GeneratorOrder.lean`): since
  `ord(G) = n`, every `k • G` satisfies `n • (k • G) = 0`.
* the `Module (ZMod n) ↥⟨G⟩` instance, built from that fact via `AddCommGroup.zmodModule`.
  Mathlib provides no automatic `ZMod n`-module on a cyclic subgroup — it must be
  constructed from the exponent bound, which is exactly what the keystone supplies.
* `secp256k1Gₙ` — the base point `G` viewed as an element of its own subgroup `⟨G⟩`.

With those in place, the protocol theorems below are *not* re-proved; they are the abstract
theorems of `Ecdlp.Schnorr` applied to `G = ↥⟨G⟩`. Their content is therefore: **the
deployed secp256k1 signature/agreement/multisig protocols are correct on the real curve
group, contingent only on the kernel-checked facts `ord(G) = n` and the abstract algebra.**
No new axioms; `secp256k1_grp_nsmul_eq_zero` inherits `Lean.ofReduceBool` from the keystone.
-/

open WeierstrassCurve.Affine

namespace Ecdlp.Curve

/-! ## The concrete carrier: the prime-order-`n` subgroup `⟨G⟩` and its `ZMod n`-module -/

/-- **`⟨G⟩`: the prime-order-`n` cyclic subgroup generated by secp256k1's base point.**
This is the concrete group Bitcoin/Ethereum ECDSA/Schnorr actually run in — the cyclic
subgroup of `E(𝔽ₚ)` generated by the standardized base point `G`, of order `n`. -/
abbrev secp256k1Grp := AddSubgroup.zmultiples secp256k1G

/-- **Every element of `⟨G⟩` is killed by `n`.** Because `ord(G) = n`
(`secp256k1_generator_addOrderOf`), every point `k • G` of the cyclic subgroup satisfies
`n • (k • G) = 0`. This is the exponent bound that turns `⟨G⟩` into a `ZMod n`-module. -/
theorem secp256k1_grp_nsmul_eq_zero (x : ↥secp256k1Grp) :
    (Secp256k1.n : ℕ) • x = 0 := by
  have hmem : (x : secp256k1.toAffine.Point) ∈ AddSubgroup.torsionBy _ (Secp256k1.n : ℤ) :=
    Ecdlp.Torsion.zmultiples_le_torsionBy
      (secp256k1_generator_addOrderOf ▸ dvd_rfl) x.2
  have hz : (Secp256k1.n : ℕ) • (x : secp256k1.toAffine.Point) = 0 := by
    rw [← addOrderOf_dvd_iff_nsmul_eq_zero]
    exact (Ecdlp.Torsion.mem_torsionBy_iff_addOrderOf_dvd _).mp hmem
  exact Subtype.ext (by simpa using hz)

/-- **The `ZMod n`-module structure on `⟨G⟩`.** Built from the exponent bound
`secp256k1_grp_nsmul_eq_zero` via `AddCommGroup.zmodModule`: scalars from `ZMod n` act on
the concrete secp256k1 subgroup, realising the abstract discrete-log model on a genuine
elliptic-curve group. -/
noncomputable instance : Module (ZMod Secp256k1.n) ↥secp256k1Grp :=
  AddCommGroup.zmodModule secp256k1_grp_nsmul_eq_zero

/-- **The base point `G`, as an element of its own subgroup `⟨G⟩`.** The scalar-multiplication
base for every protocol below is this concrete curve point. -/
def secp256k1Gₙ : ↥secp256k1Grp := ⟨secp256k1G, AddSubgroup.mem_zmultiples _⟩

/-! ## Deployed protocol correctness, on the concrete secp256k1 group

Each theorem is the corresponding abstract result of `Ecdlp.Schnorr` (proved in
`DlogCompleteness.lean`) instantiated at the concrete carrier `↥⟨G⟩` with base point
`secp256k1Gₙ`. Together they certify that the real secp256k1-based protocols are correct. -/

/-- **Diffie–Hellman key agreement on secp256k1.** Both parties derive the same shared
secret point of `⟨G⟩`: `a • (b • G) = b • (a • G)`. -/
theorem secp256k1_dh_agree (a b : ZMod Secp256k1.n) :
    a • (b • secp256k1Gₙ) = b • (a • secp256k1Gₙ) :=
  Ecdlp.Schnorr.dh_agree secp256k1Gₙ a b

/-- **Schnorr / EdDSA signature correctness on secp256k1.** An honest signature verifies:
with public key `P = x·G`, commitment `R = r·G`, response `s = r + c·x` (all over the
concrete `⟨G⟩`), the verification equation `s·G = R + c·P` holds. -/
theorem secp256k1_schnorr_verify
    (p R : ↥secp256k1Grp) (x r c s : ZMod Secp256k1.n)
    (hp : p = x • secp256k1Gₙ) (hR : R = r • secp256k1Gₙ) (hs : s = r + c * x) :
    s • secp256k1Gₙ = R + c • p :=
  Ecdlp.Schnorr.schnorr_verify secp256k1Gₙ p R x r c s hp hR hs

/-- **Bitcoin Taproot key-tweak verification (BIP-341) on secp256k1.** The output key is the
internal key tweaked by `t`: `Q = P + t·G`; a signature with the tweaked secret `x + t`
verifies against `Q`. This is the correctness of Taproot key-path spending on the real curve. -/
theorem secp256k1_taproot_tweak_verify
    (P R : ↥secp256k1Grp) (x r c t s : ZMod Secp256k1.n)
    (hP : P = x • secp256k1Gₙ) (hR : R = r • secp256k1Gₙ)
    (hs : s = r + c * (x + t)) :
    s • secp256k1Gₙ = R + c • (P + t • secp256k1Gₙ) :=
  Ecdlp.Schnorr.taproot_tweak_verify secp256k1Gₙ P R x r c t s hP hR hs

/-- **Adaptor-signature completeness on secp256k1 (atomic swaps / Lightning PTLCs).** A
pre-signature `s' = r + c·x` against adaptor point `T = t·G` adapts to `s = s' + t`, which
verifies against the `T`-shifted nonce: `s·G = (R + T) + c·P`. -/
theorem secp256k1_adaptor_complete
    (P R T : ↥secp256k1Grp) (x r c t : ZMod Secp256k1.n)
    (hP : P = x • secp256k1Gₙ) (hR : R = r • secp256k1Gₙ) (hT : T = t • secp256k1Gₙ) :
    ((r + c * x) + t) • secp256k1Gₙ = (R + T) + c • P :=
  Ecdlp.Schnorr.adaptor_complete secp256k1Gₙ P R T x r c t hP hR hT

/-- **Aggregate Schnorr / Taproot multisig correctness on secp256k1 (MuSig / FROST).** Under
a shared challenge `c`, the aggregate response verifies against the aggregate key and nonce:
`(∑ sᵢ)·G = (∑ Rᵢ) + c·(∑ Pᵢ)`. -/
theorem secp256k1_threshold_schnorr_aggregate {ι : Type*} (t : Finset ι)
    (P R : ι → ↥secp256k1Grp) (x r : ι → ZMod Secp256k1.n) (c : ZMod Secp256k1.n)
    (hP : ∀ i, P i = x i • secp256k1Gₙ) (hR : ∀ i, R i = r i • secp256k1Gₙ) :
    (∑ i ∈ t, (r i + c * x i)) • secp256k1Gₙ
      = (∑ i ∈ t, R i) + c • ∑ i ∈ t, P i :=
  Ecdlp.Schnorr.threshold_schnorr_aggregate t secp256k1Gₙ P R x r c hP hR

/-- **MuSig2 key aggregation on secp256k1.** The coefficient-weighted aggregate public key
`∑ aᵢ·Pᵢ` equals `(∑ aᵢ·xᵢ)·G`, the public key of the aggregate secret. -/
theorem secp256k1_musig_key_aggregate {ι : Type*} (t : Finset ι)
    (P : ι → ↥secp256k1Grp) (x a : ι → ZMod Secp256k1.n)
    (hP : ∀ i, P i = x i • secp256k1Gₙ) :
    (∑ i ∈ t, a i • P i) = (∑ i ∈ t, a i * x i) • secp256k1Gₙ :=
  Ecdlp.Schnorr.musig_key_aggregate t secp256k1Gₙ P x a hP

/-- **Feldman verifiable secret sharing (VSS) share verification on secp256k1.** With public
coefficient commitments `Cⱼ = aⱼ·G`, the share `s = f(i)` verifies against the commitments:
`s·G = ∑ⱼ (iʲ)·Cⱼ` — the basis of distributed key generation (DKG). -/
theorem secp256k1_feldman_vss_verify (a : ℕ → ZMod Secp256k1.n) (deg : ℕ)
    (i : ZMod Secp256k1.n) :
    (∑ j ∈ Finset.range (deg + 1), a j * i ^ j) • secp256k1Gₙ
      = ∑ j ∈ Finset.range (deg + 1), (i ^ j) • (a j • secp256k1Gₙ) :=
  Ecdlp.Schnorr.feldman_vss_verify secp256k1Gₙ a deg i

/-- **Threshold ElGamal partial-decryption combination on secp256k1.** Combining the parties'
partial decryptions `xᵢ·C₁` reconstructs the full mask `(∑ xᵢ)·C₁`. -/
theorem secp256k1_threshold_elgamal_combine {ι : Type*} (t : Finset ι)
    (C₁ : ↥secp256k1Grp) (x : ι → ZMod Secp256k1.n) :
    (∑ i ∈ t, x i • C₁) = (∑ i ∈ t, x i) • C₁ :=
  Ecdlp.Schnorr.threshold_elgamal_combine t C₁ x

/-- **Batch Schnorr verification on secp256k1.** Many signatures verify at once under
per-signature challenges `cᵢ`: `(∑ sᵢ)·G = (∑ Rᵢ) + ∑ cᵢ·Pᵢ` — the single-multi-scalar-
multiplication optimization for verifying blocks of independent Schnorr signatures. -/
theorem secp256k1_schnorr_batch_verify {ι : Type*} (t : Finset ι)
    (P R : ι → ↥secp256k1Grp) (x r c : ι → ZMod Secp256k1.n)
    (hP : ∀ i, P i = x i • secp256k1Gₙ) (hR : ∀ i, R i = r i • secp256k1Gₙ) :
    (∑ i ∈ t, (r i + c i * x i)) • secp256k1Gₙ
      = (∑ i ∈ t, R i) + ∑ i ∈ t, c i • P i :=
  Ecdlp.Schnorr.schnorr_batch_verify t secp256k1Gₙ P R x r c hP hR

end Ecdlp.Curve
