import Mathlib
import Ecdlp.Secp256k1Verified

/-! # Machine-checked primality of secp256k1 `p` (Pratt certificate, generated by `scripts/pratt_certificate.py`). Witness a=3, 10 recursive nodes. -/

namespace Ecdlp.Primality
open Nat

theorem pr_13331831 : Nat.Prime 13331831 := by
  refine lucas_primality 13331831 (13 : ZMod 13331831) (by native_decide) ?_
  intro q hq hqd
  rw [show (13331831 : ℕ) - 1 = 2 ^ 1 * (5 ^ 1 * (971 ^ 1 * (1373 ^ 1))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 971 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 1373 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_173378833005251801 : Nat.Prime 173378833005251801 := by
  refine lucas_primality 173378833005251801 (6 : ZMod 173378833005251801) (by native_decide) ?_
  intro q hq hqd
  rw [show (173378833005251801 : ℕ) - 1 = 2 ^ 3 * (5 ^ 2 * (2621 ^ 1 * (24809 ^ 1 * (13331831 ^ 1)))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2621 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 24809 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rw [(Nat.prime_dvd_prime_iff_eq hq pr_13331831).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_22149492674086928081353 : Nat.Prime 22149492674086928081353 := by
  refine lucas_primality 22149492674086928081353 (5 : ZMod 22149492674086928081353) (by native_decide) ?_
  intro q hq hqd
  rw [show (22149492674086928081353 : ℕ) - 1 = 2 ^ 3 * (3 ^ 1 * (5323 ^ 1 * (173378833005251801 ^ 1))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5323 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rw [(Nat.prime_dvd_prime_iff_eq hq pr_173378833005251801).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_132896956044521568488119 : Nat.Prime 132896956044521568488119 := by
  refine lucas_primality 132896956044521568488119 (6 : ZMod 132896956044521568488119) (by native_decide) ?_
  intro q hq hqd
  rw [show (132896956044521568488119 : ℕ) - 1 = 2 ^ 1 * (3 ^ 1 * (22149492674086928081353 ^ 1)) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rw [(Nat.prime_dvd_prime_iff_eq hq pr_22149492674086928081353).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_107590001 : Nat.Prime 107590001 := by
  refine lucas_primality 107590001 (3 : ZMod 107590001) (by native_decide) ?_
  intro q hq hqd
  rw [show (107590001 : ℕ) - 1 = 2 ^ 4 * (5 ^ 4 * (7 ^ 1 * (29 ^ 1 * (53 ^ 1)))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 7 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 29 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 53 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_1206781 : Nat.Prime 1206781 := by
  refine lucas_primality 1206781 (10 : ZMod 1206781) (by native_decide) ?_
  intro q hq hqd
  rw [show (1206781 : ℕ) - 1 = 2 ^ 2 * (3 ^ 1 * (5 ^ 1 * (20113 ^ 1))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 20113 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_7240687 : Nat.Prime 7240687 := by
  refine lucas_primality 7240687 (3 : ZMod 7240687) (by native_decide) ?_
  intro q hq hqd
  rw [show (7240687 : ℕ) - 1 = 2 ^ 1 * (3 ^ 1 * (1206781 ^ 1)) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rw [(Nat.prime_dvd_prime_iff_eq hq pr_1206781).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_255515944373312847190720520512484175977 : Nat.Prime 255515944373312847190720520512484175977 := by
  refine lucas_primality 255515944373312847190720520512484175977 (3 : ZMod 255515944373312847190720520512484175977) (by native_decide) ?_
  intro q hq hqd
  rw [show (255515944373312847190720520512484175977 : ℕ) - 1 = 2 ^ 3 * (7 ^ 2 * (11 ^ 1 * (1627 ^ 1 * (2657 ^ 1 * (4423 ^ 1 * (96557 ^ 1 * (41201 ^ 1 * (107590001 ^ 1 * (7240687 ^ 1))))))))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 7 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 11 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 1627 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2657 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
          ·
            rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 4423 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
            ·
              rcases (Nat.Prime.dvd_mul hq).mp h with h | h
              · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 96557 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
              ·
                rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 41201 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
                ·
                  rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                  · rw [(Nat.prime_dvd_prime_iff_eq hq pr_107590001).mp (hq.dvd_of_dvd_pow h)]; native_decide
                  ·
                    rw [(Nat.prime_dvd_prime_iff_eq hq pr_7240687).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_205115282021455665897114700593932402728804164701536103180137503955397371 : Nat.Prime 205115282021455665897114700593932402728804164701536103180137503955397371 := by
  refine lucas_primality 205115282021455665897114700593932402728804164701536103180137503955397371 (10 : ZMod 205115282021455665897114700593932402728804164701536103180137503955397371) (by native_decide) ?_
  intro q hq hqd
  rw [show (205115282021455665897114700593932402728804164701536103180137503955397371 : ℕ) - 1 = 2 ^ 1 * (3 ^ 1 * (5 ^ 1 * (29 ^ 2 * (31 ^ 1 * (7723 ^ 1 * (132896956044521568488119 ^ 1 * (255515944373312847190720520512484175977 ^ 1))))))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 5 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 29 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 31 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
          ·
            rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 7723 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
            ·
              rcases (Nat.Prime.dvd_mul hq).mp h with h | h
              · rw [(Nat.prime_dvd_prime_iff_eq hq pr_132896956044521568488119).mp (hq.dvd_of_dvd_pow h)]; native_decide
              ·
                rw [(Nat.prime_dvd_prime_iff_eq hq pr_255515944373312847190720520512484175977).mp (hq.dvd_of_dvd_pow h)]; native_decide

theorem pr_115792089237316195423570985008687907853269984665640564039457584007908834671663 : Nat.Prime 115792089237316195423570985008687907853269984665640564039457584007908834671663 := by
  refine lucas_primality 115792089237316195423570985008687907853269984665640564039457584007908834671663 (3 : ZMod 115792089237316195423570985008687907853269984665640564039457584007908834671663) (by native_decide) ?_
  intro q hq hqd
  rw [show (115792089237316195423570985008687907853269984665640564039457584007908834671663 : ℕ) - 1 = 2 ^ 1 * (3 ^ 1 * (7 ^ 1 * (13441 ^ 1 * (205115282021455665897114700593932402728804164701536103180137503955397371 ^ 1)))) by native_decide] at hqd
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 2 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
  ·
    rcases (Nat.Prime.dvd_mul hq).mp h with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 3 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
    ·
      rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 7 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
      ·
        rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (show Nat.Prime 13441 by norm_num)).mp (hq.dvd_of_dvd_pow h)]; native_decide
        ·
          rw [(Nat.prime_dvd_prime_iff_eq hq pr_205115282021455665897114700593932402728804164701536103180137503955397371).mp (hq.dvd_of_dvd_pow h)]; native_decide

/-- secp256k1 p is prime (full Pratt certificate). -/
theorem secp256k1_p_prime : Nat.Prime Secp256k1.p := pr_115792089237316195423570985008687907853269984665640564039457584007908834671663

instance : Fact (Nat.Prime Secp256k1.p) := ⟨secp256k1_p_prime⟩

end Ecdlp.Primality

