import Ecdlp.Proved.ProtocolInstantiation

/-!
# The discrete-log group structure of secp256k1's subgroup `⟨G⟩`

`ProtocolInstantiation.lean` realises the abstract `ZMod n`-module model on the concrete
cyclic subgroup `⟨G⟩ = zmultiples secp256k1G`. This file records the *structure* of that
group: it has exactly `n` elements, is cyclic, and — the precise statement underlying the
elliptic-curve discrete-log problem — the base-point-multiplication map `c ↦ c·G` is a
**group isomorphism** `ZMod n ≃+ ⟨G⟩`.

Everything rests on the weak point-counting keystone `addOrderOf secp256k1G = n`
(`GeneratorOrder.lean`); no Hasse / `#E` is used. The isomorphism says exactly that the
discrete log is a well-defined bijection `⟨G⟩ → ZMod n` — its *hardness* is the open ECDLP
conjecture, of which this states only the (unconditional) group-theoretic shape.
-/

open WeierstrassCurve.Affine

namespace Ecdlp.Curve

/-- **`⟨G⟩` has exactly `n` elements.** The concrete secp256k1 crypto subgroup is finite of
cardinality `n`, from `Nat.card (zmultiples g) = addOrderOf g` and `addOrderOf G = n`. -/
theorem secp256k1_grp_card : Nat.card ↥secp256k1Grp = Secp256k1.n := by
  rw [Nat.card_zmultiples, secp256k1_generator_addOrderOf]

/-- **`⟨G⟩` is a cyclic additive group** (generated by the single base point). -/
theorem secp256k1_grp_isAddCyclic : IsAddCyclic ↥secp256k1Grp := inferInstance

/-- The base point `G`, viewed inside its own subgroup `⟨G⟩`, has additive order `n`. -/
theorem secp256k1_gen_addOrderOf : addOrderOf secp256k1Gₙ = Secp256k1.n := by
  have h : addOrderOf (secp256k1Grp.subtype secp256k1Gₙ) = addOrderOf secp256k1Gₙ :=
    addOrderOf_injective secp256k1Grp.subtype Subtype.coe_injective secp256k1Gₙ
  rw [← h]; exact secp256k1_generator_addOrderOf

/-- The discrete-log map `c ↦ c·G` as an additive homomorphism `ZMod n →+ ⟨G⟩`. -/
noncomputable def secp256k1_dlogHom : ZMod Secp256k1.n →+ ↥secp256k1Grp :=
  (smulAddHom (ZMod Secp256k1.n) ↥secp256k1Grp).flip secp256k1Gₙ

@[simp] theorem secp256k1_dlogHom_apply (c : ZMod Secp256k1.n) :
    secp256k1_dlogHom c = c • secp256k1Gₙ := rfl

/-- The discrete-log map is injective: distinct scalars give distinct points (via
`addOrderOf G = n` and `c.val < n`). -/
theorem secp256k1_dlogHom_injective : Function.Injective secp256k1_dlogHom := by
  rw [injective_iff_map_eq_zero]
  intro c hc
  rw [secp256k1_dlogHom_apply] at hc
  have h0 : (c.val : ℕ) • secp256k1Gₙ = 0 := by
    rw [← Nat.cast_smul_eq_nsmul (R := ZMod Secp256k1.n), ZMod.natCast_rightInverse c]
    exact hc
  have hdvd : addOrderOf secp256k1Gₙ ∣ c.val := addOrderOf_dvd_of_nsmul_eq_zero h0
  rw [secp256k1_gen_addOrderOf] at hdvd
  exact (ZMod.val_eq_zero c).mp (Nat.eq_zero_of_dvd_of_lt hdvd (ZMod.val_lt c))

/-- The discrete-log map is surjective: every point of `⟨G⟩` is `c·G` for some scalar. -/
theorem secp256k1_dlogHom_surjective : Function.Surjective secp256k1_dlogHom := by
  intro y
  obtain ⟨k, hk⟩ := AddSubgroup.mem_zmultiples_iff.mp y.2
  refine ⟨(k : ZMod Secp256k1.n), ?_⟩
  rw [secp256k1_dlogHom_apply, Int.cast_smul_eq_zsmul]
  apply Subtype.ext
  rw [AddSubgroup.coe_zsmul]
  exact hk

/-- **The discrete-log map is a group isomorphism `ZMod n ≃+ ⟨G⟩`.** The base-point
multiplication `c ↦ c·G` is an additive-group isomorphism between the scalar ring `ZMod n`
and the concrete secp256k1 subgroup `⟨G⟩`. This is the exact group-theoretic content of the
elliptic-curve discrete-log setting: `dlog = (c ↦ c·G)⁻¹` is a well-defined bijection.
Its *computational* inversion is the open ECDLP hardness conjecture; this theorem asserts
only the unconditional bijection, from `addOrderOf G = n`. -/
noncomputable def secp256k1_dlogEquiv : ZMod Secp256k1.n ≃+ ↥secp256k1Grp :=
  AddEquiv.ofBijective secp256k1_dlogHom
    ⟨secp256k1_dlogHom_injective, secp256k1_dlogHom_surjective⟩

@[simp] theorem secp256k1_dlogEquiv_apply (c : ZMod Secp256k1.n) :
    secp256k1_dlogEquiv c = c • secp256k1Gₙ := rfl

end Ecdlp.Curve
