import Mathlib

/-!
# The n-torsion subgroup `E[n]` — bridge to Mathlib and to the discrete-log model

`notes/FOUNDATIONS.md` lists "`n`-torsion subgroup `E[n]` as a group object" as the
first deep-foundations rung toward the Weil pairing. Mathlib already provides it:
`AddSubgroup.torsionBy A n` (notation `A[n]`) is the subgroup `{x | n • x = 0}` of any
`AddCommGroup`, with a `Module (ZMod n)` structure (`torsionBy.zmodModule`). So `E[n]`
is *available* for the secp256k1 point group `WeierstrassCurve.Affine.Point` for free.

This file records the genuinely-new connective tissue that the bare definition does not
give:

* `mem_torsionBy_iff_addOrderOf_dvd` — the order characterization: a point lies in `E[n]`
  iff its order divides `n`. This is the abstract content of "`[n]P = O ⟺ ord(P) ∣ n`"
  and the reason `⟨G⟩ ⊆ E[n]` whenever `ord(G) ∣ n`.
* `torsionBy_dvd_le` — the torsion filtration `E[m] ≤ E[n]` for `m ∣ n` (so `E[m]` grows
  monotonically along divisibility, e.g. `E[2] ⊆ E[2k]`).
* `zmod_module_nsmul_eq_zero` / `torsionBy_eq_top` — the bridge to the discrete-log model
  used throughout `DlogCompleteness.lean`/`DlogPrimitives.lean`: a `ZMod n`-module is its
  own `n`-torsion (`G[n] = ⊤`), i.e. the whole DL group is `n`-torsion. For secp256k1
  (cofactor 1) this is the abstract shape of "every curve point has order dividing `n`".

All of this is general `AddCommGroup` / `Module (ZMod n)` algebra — kernel-checked, no
new axioms — and applies verbatim to the elliptic-curve point group.
-/

namespace Ecdlp.Torsion

/-! ## Order characterization and the torsion filtration (any `AddCommGroup`) -/

variable {A : Type*} [AddCommGroup A]

/-- **`E[n]` is exactly the points of order dividing `n`.** A point lies in the
`n`-torsion subgroup iff its additive order divides `n`. This is the abstract form of
`[n]P = O ⟺ ord(P) ∣ n`; in particular the cyclic group `⟨G⟩` generated by a point of
order `n` lies inside `E[n]`. -/
theorem mem_torsionBy_iff_addOrderOf_dvd {n : ℕ} (x : A) :
    x ∈ AddSubgroup.torsionBy A (n : ℤ) ↔ addOrderOf x ∣ n := by
  rw [AddSubgroup.torsionBy.nsmul_iff, ← addOrderOf_dvd_iff_nsmul_eq_zero]

/-- **The torsion filtration: `E[m] ≤ E[n]` when `m ∣ n`.** Torsion subgroups grow
monotonically along divisibility — every `m`-torsion point is `n`-torsion when `m ∣ n`
(so e.g. `E[2] ⊆ E[6]`). The building block for reasoning about the lattice of torsion
subgroups. -/
theorem torsionBy_dvd_le {m k : ℤ} (h : m ∣ k) :
    AddSubgroup.torsionBy A m ≤ AddSubgroup.torsionBy A k :=
  Submodule.toAddSubgroup_mono (Submodule.torsionBy_le_torsionBy_of_dvd m k h)

/-! ## Bridge to the discrete-log model: a `ZMod n`-module is its own `n`-torsion -/

variable {n : ℕ} [Module (ZMod n) A]

/-- **A `ZMod n`-module is killed by `n`.** Every element of the discrete-log group
(modelled as a `ZMod n`-module, exponent dividing `n`) satisfies `n • x = 0`: scalar `n`
acts as `0` because `(n : ZMod n) = 0`. -/
theorem zmod_module_nsmul_eq_zero (x : A) : n • x = 0 := by
  rw [← Nat.cast_smul_eq_nsmul (R := ZMod n) n x, ZMod.natCast_self, zero_smul]

/-- **The whole DL group is its `n`-torsion: `G[n] = ⊤`.** The cyclic group used to model
discrete-log cryptography (`Module (ZMod n) G`) coincides with its own `n`-torsion
subgroup. For secp256k1, whose cofactor is `1`, this is the abstract shape of "every curve
point has order dividing `n`" — `E(𝔽ₚ) = E[n]`. -/
theorem torsionBy_eq_top : AddSubgroup.torsionBy A (n : ℤ) = ⊤ := by
  rw [eq_top_iff]
  intro x _
  rw [AddSubgroup.torsionBy.nsmul_iff]
  exact zmod_module_nsmul_eq_zero x

end Ecdlp.Torsion
