import Mathlib

/-!
# UORC-056 C44 Ward open-transport boundary

This file kernel-checks the small algebraic core of C44:

* a multiplicative sign expression generated by two involutive states has only
  four variable classes;
* multiplying expressions combines the two class bits by exclusive-or;
* 32 transport cycles with one anchored cycle leave 31 Boolean choices;
* exact secp256k1 component-count arithmetic.

The division-polynomial identities, exact secp256k1 multiplicative-order
certificates, and fixed witness evaluations are replayed by the companion
Python program. This file does not claim a parity oracle or a complexity lower
bound for unrestricted full-field transports.
-/

namespace Ecdlp.Uorc056WardOpenTransportC44


def bitXor : Bool → Bool → Bool
  | false, b => b
  | true, false => true
  | true, true => false


def bitPow {G : Type*} [Monoid G] (x : G) : Bool → G
  | false => 1
  | true => x


theorem bitPow_mul_of_sq_one
    {G : Type*} [Monoid G]
    (x : G) (hx : x * x = 1) (a b : Bool) :
    bitPow x a * bitPow x b = bitPow x (bitXor a b) := by
  cases a <;> cases b <;> simp [bitPow, bitXor, hx]


def wardVariableClass
    {G : Type*} [CommMonoid G]
    (near nearNext : G) (alpha beta : Bool) : G :=
  bitPow near alpha * bitPow nearNext beta


/-- Arbitrary finite multiplication never leaves the four classes generated by
`near` and `nearNext`, provided both are signs (their squares are one). -/
theorem wardVariableClass_mul
    {G : Type*} [CommMonoid G]
    (near nearNext : G)
    (hnear : near * near = 1)
    (hnext : nearNext * nearNext = 1)
    (alpha beta gamma delta : Bool) :
    wardVariableClass near nearNext alpha beta *
        wardVariableClass near nearNext gamma delta =
      wardVariableClass near nearNext
        (bitXor alpha gamma) (bitXor beta delta) := by
  unfold wardVariableClass
  calc
    bitPow near alpha * bitPow nearNext beta *
        (bitPow near gamma * bitPow nearNext delta) =
      (bitPow near alpha * bitPow near gamma) *
        (bitPow nearNext beta * bitPow nearNext delta) := by
          ac_rfl
    _ = bitPow near (bitXor alpha gamma) *
        bitPow nearNext (bitXor beta delta) := by
          rw [bitPow_mul_of_sq_one near hnear]
          rw [bitPow_mul_of_sq_one nearNext hnext]


/-- An exact mismatch at one public witness rules out a proposed all-input
identity. -/
theorem witness_refutes_global_identity
    {I V : Type*} (candidate target : I → V) (i : I)
    (hne : candidate i ≠ target i) : candidate ≠ target := by
  intro h
  exact hne (congrFun h i)


def secpN : Nat :=
  0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141


def secpPairComponents : Nat :=
  (secpN - 1) / 2


def secpOrderTwo : Nat :=
  (secpN - 1) / 64


theorem secpCorrectedDoublingCycleCount :
    secpPairComponents / secpOrderTwo = 32 := by
  native_decide


theorem oneAnchorLeavesThirtyOneBinaryChoices :
    Fintype.card (Fin 31 → Bool) = 2 ^ 31 := by
  simp


theorem residualAssignmentCount :
    2 ^ 31 = 2147483648 := by
  native_decide

end Ecdlp.Uorc056WardOpenTransportC44
