import Mathlib

/-!
# UORC-056 C46 geometric first-jet collapse

The executable replay proves, on the declared elliptic-curve instances,

    J_n(Q) = -n * Phi_raw(Q)^(-n^2).

This file kernel-checks the elementary algebraic consequence: once that
identity is known, the geometric first jet is fully determined by the raw
state and contributes no second independent field coordinate.

The dual-number division-polynomial recurrence and elliptic-curve derivative
identity are replayed by Python and are not mislabeled here as fully
formalized. This file does not address the distinct p-adic arithmetic jet.
-/

namespace Ecdlp.Uorc056FirstJetRawCollapseC46


def jetFromRaw
    {G : Type*} [Group G]
    (raw scale : G) (exponent : Nat) : G :=
  scale * (raw ^ exponent)⁻¹


/-- Multiplying the collapsed jet by its public raw-state power recovers only
its public scale. Thus the jet contains no independent group-valued factor. -/
theorem jetFromRaw_recoverScale
    {G : Type*} [Group G]
    (raw scale : G) (exponent : Nat) :
    jetFromRaw raw scale exponent * raw ^ exponent = scale := by
  simp [jetFromRaw, mul_assoc]


/-- Equal raw states necessarily give equal collapsed jets. -/
theorem equalRaw_equalJet
    {G : Type*} [Group G]
    (raw₁ raw₂ scale : G) (exponent : Nat)
    (hraw : raw₁ = raw₂) :
    jetFromRaw raw₁ scale exponent =
      jetFromRaw raw₂ scale exponent := by
  rw [hraw]


/-- A multiplicative readout of the collapsed jet is likewise generated by the
readouts of the public scale and raw state. -/
theorem map_jetFromRaw
    {G H : Type*} [Group G] [Group H]
    (f : G →* H) (raw scale : G) (exponent : Nat) :
    f (jetFromRaw raw scale exponent) =
      f scale * (f raw ^ exponent)⁻¹ := by
  simp [jetFromRaw]


def declaredSamples : Nat := 294

def declaredCurves : Nat := 9


theorem declaredRawCollapseCount : declaredSamples = 294 := by
  native_decide


theorem declaredGeneratorJetCount : declaredCurves = 9 := by
  native_decide


theorem declaredTripleCheckCount : 3 * declaredSamples = 882 := by
  native_decide

end Ecdlp.Uorc056FirstJetRawCollapseC46
