#!/usr/bin/env python3
"""Render the canonical secp256k1 ECDLP decision substrate.

The JSON owns project decisions. This script emits a compact human-readable view
without creating a second hand-maintained source of truth.

Usage:
  python scripts/build_ecdlp_decision_view.py
  python scripts/build_ecdlp_decision_view.py --check
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "repo" / "ECDLP_DECISION_SUBSTRATE.json"
SOURCE_REGISTRY = ROOT / "data" / "source_registry.json"
OUT = ROOT / "repo" / "ECDLP_DECISION_SUBSTRATE.md"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def refs(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) or "-"


def source_link(source_id: str, sources: dict[str, dict]) -> str:
    source = sources.get(source_id)
    if source is None:
        return f"`{source_id}`"
    target = source.get("url")
    if not target and source.get("doi"):
        target = f"https://doi.org/{source['doi']}"
    label = f"{source_id}: {source['title']}"
    return f"[{label}]({target})" if target else f"`{label}`"


def render(data: dict, sources: dict[str, dict]) -> str:
    target = data["target_problem"]
    policy = data["phase_policy"]
    selection = data["route_selection"]
    lines = [
        "# secp256k1 ECDLP decision substrate",
        "",
        "> Generated by `scripts/build_ecdlp_decision_view.py` from "
        "`repo/ECDLP_DECISION_SUBSTRATE.json`. Edit the JSON, not this file.",
        "",
        "## Exact objective",
        "",
        f"Given {', '.join(target['inputs'])}, **{target['output']}**",
        "",
        f"Current phase: **{policy['phase']}**. Experiments authorized: "
        f"**{str(policy['experiments_authorized']).lower()}**. Selected route: "
        f"**{policy['selected_attack_route'] or 'none'}**.",
        "",
        "The formal-result map, attack encyclopedia, and this decision layer are "
        "deliberately distinct:",
        "",
    ]
    for key, path in data["canonical_ownership"].items():
        lines.append(f"- **{key}:** `{path}`")

    lines.extend(
        [
            "",
            "## Current route selection",
            "",
            f"Decision **{selection['decision_id']}** on "
            f"`{selection['performed_on']}`: **{selection['decision']}**.",
            "",
            selection["gate_result"],
            "",
            "Rationale:",
            "",
        ]
    )
    for reason in selection["rationale"]:
        lines.append(f"- {reason}")
    lines.extend(["", "Reopen selection only when:"])
    for trigger in selection["reconsideration_triggers"]:
        lines.append(f"- {trigger}")

    lines.extend(
        [
            "",
            "## Threat models",
            "",
            "| model | primary | definition |",
            "|---|---:|---|",
        ]
    )
    for model in data["threat_models"]:
        lines.append(
            f"| `{model['id']}` | {str(model['primary']).lower()} | "
            f"{cell(model['definition'])} |"
        )

    lines.extend(
        [
            "",
            "## Route decisions",
            "",
            "| priority | route | disposition | threat model | next action |",
            "|---:|---|---|---|---|",
        ]
    )
    for route in sorted(data["routes"], key=lambda item: (item["priority"], item["id"])):
        lines.append(
            f"| {route['priority']} | **{route['id']}**: {cell(route['title'])} | "
            f"`{route['status']}` | {refs(route['threat_models'])} | "
            f"{cell(route['next_action'])} |"
        )

    lines.extend(["", "## Route evidence", ""])
    for route in sorted(data["routes"], key=lambda item: (item["priority"], item["id"])):
        lines.extend(
            [
                f"### {route['id']}: {route['title']}",
                "",
                f"- **Applicability:** {route['applicability']}",
                f"- **Known cost:** {route['known_cost']}",
                f"- **Evidence:** {route['current_evidence']}",
                f"- **Promotion gate:** {route['success_gate']}",
                f"- **Stop condition:** {route['stop_condition']}",
                f"- **Anti-overclaim:** {route['anti_overclaim']}",
                f"- **Foundations:** {refs(route['foundation_ids'])}",
                f"- **Formal nodes:** {refs(route['formal_node_ids'])}",
                f"- **Lean anchors:** {refs(route['lean_anchors'])}",
                f"- **Repository evidence:** {refs(route['evidence_files'])}",
            ]
        )
        source_items = [
            source_link(source_id, sources) for source_id in route["source_ids"]
        ]
        lines.append(
            "- **Primary sources:** " + (", ".join(source_items) if source_items else "-")
        )
        lines.append("")

    lines.extend(
        [
            "## Foundation decisions",
            "",
            "| priority | foundation | decision | status | build now | resume condition |",
            "|---:|---|---|---|---:|---|",
        ]
    )
    for foundation in sorted(
        data["foundations"], key=lambda item: (item["priority"], item["id"])
    ):
        lines.append(
            f"| {foundation['priority']} | **{foundation['id']}**: "
            f"{cell(foundation['title'])} | `{foundation['decision']}` | "
            f"`{foundation['implementation_status']}` | "
            f"{str(foundation['build_now']).lower()} | "
            f"{cell(foundation['resume_condition'])} |"
        )

    lines.extend(["", "### Upstream Mathlib snapshot", ""])
    upstream = data["upstream_snapshot"]
    lines.extend(
        [
            f"- Audited: `{upstream['audited_on']}`",
            f"- Project pin: `{upstream['project_mathlib_pin']['tag']}` / "
            f"`{upstream['project_mathlib_pin']['commit']}`",
            f"- Observed master: `{upstream['mathlib_master_observed']['commit']}`",
            f"- Method caveat: {upstream['method']}",
            "",
        ]
    )
    for qualification in upstream["important_qualifications"]:
        lines.append(f"- {qualification}")

    literature = data["literature_snapshot"]
    quantum = literature["current_quantum_update"]
    lines.extend(
        [
            "",
            "## Literature boundary",
            "",
            literature["bounded_conclusion"],
            "",
            f"The tracked 2026 quantum update (`{quantum['source_id']}`) reports "
            f"**{quantum['reported_secp256k1_resources']['logical_qubits']} logical "
            "qubits** and **2^"
            f"{quantum['reported_secp256k1_resources']['toffoli_gates_log2']} Toffoli "
            f"gates**. {quantum['claim_scope']}",
            "",
            "## Promotion and review",
            "",
        ]
    )
    for requirement in data["next_phase_gate"]["reopen_requirements"]:
        lines.append(f"- {requirement}")
    lines.extend(
        [
            "",
            f"**Route selection:** {data['next_phase_gate']['decision']}",
            "",
            f"**Final review:** {data['next_phase_gate']['final_review']}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    data = load_json(SOURCE)
    registry = load_json(SOURCE_REGISTRY)
    sources = {source["id"]: source for source in registry["sources"]}
    rendered = render(data, sources)

    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != rendered:
            print(
                "decision view is stale; run "
                "`python scripts/build_ecdlp_decision_view.py`",
                file=sys.stderr,
            )
            return 1
        print(
            f"decision view OK: {len(data['routes'])} routes, "
            f"{len(data['foundations'])} foundations."
        )
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(data['routes'])} routes, "
        f"{len(data['foundations'])} foundations."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
