#!/usr/bin/env python3
"""Render the canonical secp256k1 ECDLP decision substrate.

The JSON owns project decisions. This script emits a compact human-readable view
without creating a second hand-maintained source of truth.

Usage:
  python scripts/build_ecdlp_decision_view.py
  python scripts/build_ecdlp_decision_view.py --check
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "repo" / "ECDLP_DECISION_SUBSTRATE.json"
SOURCE_REGISTRY = ROOT / "data" / "source_registry.json"
OUT = ROOT / "repo" / "ECDLP_DECISION_SUBSTRATE.md"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def refs(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) or "-"


def source_link(source_id: str, sources: dict[str, dict]) -> str:
    source = sources.get(source_id)
    if source is None:
        return f"`{source_id}`"
    target = source.get("url")
    if not target and source.get("doi"):
        target = f"https://doi.org/{source['doi']}"
    label = f"{source_id}: {source['title']}"
    return f"[{label}]({target})" if target else f"`{label}`"


def render(data: dict, sources: dict[str, dict]) -> str:
    target = data["target_problem"]
    policy = data["phase_policy"]
    authorization = data["bounded_experiment_authorization"]
    selection = data["route_selection"]
    selected_structural = selection.get("selected_route_ids", [])
    promoted = selection.get("promoted_route_ids", [])
    lines = [
        "# secp256k1 ECDLP decision substrate",
        "",
        "> Generated by `scripts/build_ecdlp_decision_view.py` from "
        "`repo/ECDLP_DECISION_SUBSTRATE.json`. Edit the JSON, not this file.",
        "",
        "## Exact objective",
        "",
        f"Given {', '.join(target['inputs'])}, **{target['output']}**",
        "",
        f"Current phase: **{policy['phase']}**. Exact decision experiment "
        f"authorized: **{str(policy['experiments_authorized']).lower()}**. "
        f"Native bounded exploration authorized: "
        f"**{str(policy['bounded_exploration_authorized']).lower()}**. Promotion "
        f"experiments authorized: "
        f"**{str(policy['promotion_experiments_authorized']).lower()}**. "
        f"Selected promoted route: **{policy['selected_attack_route'] or 'none'}**.",
        "",
        f"Bounded structural routes recorded by the decision: **{len(selected_structural)}** "
        f"({refs(selected_structural)}). Promoted routes: **{len(promoted)}** "
        f"({refs(promoted)}).",
        "",
        "## Exact bounded experiment record",
        "",
        f"Authorization **{authorization['authorization_id']}** is "
        f"**{authorization['status']}** for exactly hypothesis "
        f"**{authorization['hypothesis_id']}**, task "
        f"**{authorization['task_id']}**, route "
        f"**{authorization['route_id']}**, and cell "
        f"**{authorization['cell_id']}**.",
        "",
        f"- **Readiness source commit:** `{authorization['source_commit']}`",
        f"- **Authorized UTC:** `{authorization['authorized_utc']}`",
        f"- **Completed UTC:** `{authorization['completed_utc']}`",
        f"- **Terminal event:** `{authorization['terminal_event_id']}`",
        f"- **Terminal:** `{authorization['terminal_status']}`",
        f"- **Normalized enabling outcome:** "
        f"`{authorization['normalized_outcome']}`",
        f"- **Validated artifact SHA-256:** "
        f"`{authorization['validated_artifact_sha256']}`",
        f"- **Rerun authorized:** "
        f"**{str(authorization['rerun_authorized']).lower()}**",
        f"- **Scope:** `{authorization['scope']['kind']}` on "
        f"`{authorization['scope']['curve_family']}` curves "
        f"{refs(authorization['scope']['curve_ids'])}; maximum field size "
        f"**{authorization['scope']['max_field_bits']} bits**",
        f"- **Primary-trial ceiling:** "
        f"**{authorization['resource_budget']['max_primary_trials']}**",
        f"- **Resource ceilings:** "
        f"**{authorization['resource_budget']['max_cpu_hours']} CPU-hours**, "
        f"**{authorization['resource_budget']['max_peak_rss_gib']} GiB peak RSS**, "
        f"**{authorization['resource_budget']['max_wall_hours']} wall-hours**",
        f"- **Real-world targets forbidden:** "
        f"**{str(authorization['scope']['real_world_targets_forbidden']).lower()}**",
        f"- **secp256k1 targets forbidden:** "
        f"**{str(authorization['scope']['secp256k1_targets_forbidden']).lower()}**",
        f"- **Promotion authorized:** "
        f"**{str(authorization['promotion_authorized']).lower()}**",
        "",
        "The five readiness files are content-bound:",
        "",
    ]
    for name, digest in authorization["sha256_bindings"].items():
        lines.append(f"- `{name}`: `{digest}`")
    lines.extend(
        [
        "",
        "This singleton is external to the native Research Engine candidate "
        "queue. It does not authorize another experiment, a solver, route "
        "promotion, exact-target work, or a secp256k1 extrapolation.",
        "",
        "The formal-result map, attack encyclopedia, and this decision layer are "
        "deliberately distinct:",
        "",
        ]
    )
    for key, path in data["canonical_ownership"].items():
        lines.append(f"- **{key}:** `{path}`")

    lines.extend(
        [
            "",
            "## Current route selection",
            "",
            f"Decision **{selection['decision_id']}** on "
            f"`{selection['performed_on']}`: **{selection['decision']}**.",
            "",
            selection["gate_result"],
            "",
            f"Iteration: **{selection.get('iteration_id', 'none')}**. "
            f"Hypothesis: **{selection.get('hypothesis_id', 'none')}**. "
            f"Task: **{selection.get('task_id', 'none')}**.",
            "",
            "Rationale:",
            "",
        ]
    )
    for reason in selection["rationale"]:
        lines.append(f"- {reason}")
    lines.extend(["", "Reopen selection only when:"])
    for trigger in selection["reconsideration_triggers"]:
        lines.append(f"- {trigger}")

    lines.extend(
        [
            "",
            "## Threat models",
            "",
            "| model | primary | definition |",
            "|---|---:|---|",
        ]
    )
    for model in data["threat_models"]:
        lines.append(
            f"| `{model['id']}` | {str(model['primary']).lower()} | "
            f"{cell(model['definition'])} |"
        )

    lines.extend(
        [
            "",
            "## Route decisions",
            "",
            "| priority | route | disposition | threat model | next action |",
            "|---:|---|---|---|---|",
        ]
    )
    for route in sorted(data["routes"], key=lambda item: (item["priority"], item["id"])):
        lines.append(
            f"| {route['priority']} | **{route['id']}**: {cell(route['title'])} | "
            f"`{route['status']}` | {refs(route['threat_models'])} | "
            f"{cell(route['next_action'])} |"
        )

    lines.extend(["", "## Route evidence", ""])
    for route in sorted(data["routes"], key=lambda item: (item["priority"], item["id"])):
        lines.extend(
            [
                f"### {route['id']}: {route['title']}",
                "",
                f"- **Applicability:** {route['applicability']}",
                f"- **Known cost:** {route['known_cost']}",
                f"- **Evidence:** {route['current_evidence']}",
                f"- **Promotion gate:** {route['success_gate']}",
                f"- **Stop condition:** {route['stop_condition']}",
                f"- **Anti-overclaim:** {route['anti_overclaim']}",
                f"- **Foundations:** {refs(route['foundation_ids'])}",
                f"- **Formal nodes:** {refs(route['formal_node_ids'])}",
                f"- **Lean anchors:** {refs(route['lean_anchors'])}",
                f"- **Repository evidence:** {refs(route['evidence_files'])}",
            ]
        )
        if route.get("structural_lane"):
            work = route["structural_lane"]
            lines.extend(
                [
                    f"- **Structural iteration:** `{work['iteration_id']}`",
                    f"- **Structural scope:** {work['scope']}",
                    f"- **Structural status:** `{work['status']}`",
                ]
            )
        source_items = [
            source_link(source_id, sources) for source_id in route["source_ids"]
        ]
        lines.append(
            "- **Primary sources:** " + (", ".join(source_items) if source_items else "-")
        )
        lines.append("")

    lines.extend(
        [
            "## Foundation decisions",
            "",
            "| priority | foundation | decision | status | build now | resume condition |",
            "|---:|---|---|---|---:|---|",
        ]
    )
    for foundation in sorted(
        data["foundations"], key=lambda item: (item["priority"], item["id"])
    ):
        lines.append(
            f"| {foundation['priority']} | **{foundation['id']}**: "
            f"{cell(foundation['title'])} | `{foundation['decision']}` | "
            f"`{foundation['implementation_status']}` | "
            f"{str(foundation['build_now']).lower()} | "
            f"{cell(foundation['resume_condition'])} |"
        )

    lines.extend(["", "### Upstream Mathlib snapshot", ""])
    upstream = data["upstream_snapshot"]
    lines.extend(
        [
            f"- Audited: `{upstream['audited_on']}`",
            f"- Project pin: `{upstream['project_mathlib_pin']['tag']}` / "
            f"`{upstream['project_mathlib_pin']['commit']}`",
            f"- Observed master: `{upstream['mathlib_master_observed']['commit']}`",
            f"- Method caveat: {upstream['method']}",
            "",
        ]
    )
    for qualification in upstream["important_qualifications"]:
        lines.append(f"- {qualification}")

    literature = data["literature_snapshot"]
    quantum = literature["current_quantum_update"]
    lines.extend(
        [
            "",
            "## Literature boundary",
            "",
            literature["bounded_conclusion"],
            "",
            f"The tracked 2026 quantum update (`{quantum['source_id']}`) reports "
            f"**{quantum['reported_secp256k1_resources']['logical_qubits']} logical "
            "qubits** and **2^"
            f"{quantum['reported_secp256k1_resources']['toffoli_gates_log2']} Toffoli "
            f"gates**. {quantum['claim_scope']}",
            "",
            "## Promotion and review",
            "",
        ]
    )
    for requirement in data["next_phase_gate"]["reopen_requirements"]:
        lines.append(f"- {requirement}")
    lines.extend(
        [
            "",
            f"**Current phase gate:** {data['next_phase_gate']['decision']}",
            "",
            f"**Final review:** {data['next_phase_gate']['final_review']}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    data = load_json(SOURCE)
    registry = load_json(SOURCE_REGISTRY)
    sources = {source["id"]: source for source in registry["sources"]}
    rendered = render(data, sources)

    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != rendered:
            print(
                "decision view is stale; run "
                "`python scripts/build_ecdlp_decision_view.py`",
                file=sys.stderr,
            )
            return 1
        print(
            f"decision view OK: {len(data['routes'])} routes, "
            f"{len(data['foundations'])} foundations."
        )
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(data['routes'])} routes, "
        f"{len(data['foundations'])} foundations."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
