#!/usr/bin/env python3
"""Generate the exhaustive #print axioms audit from the result registry."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "data" / "result_registry.json"
OUT = ROOT / "Ecdlp" / "LedgerAxiomAudit.lean"


def render() -> str:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    names = registry.get("ledger_declarations", [])
    lines = [
        "import Ecdlp",
        "import ResearchOS",
        "",
        "/-!",
        "# Generated exhaustive ledger axiom audit",
        "",
        "Generated by `scripts/gen_axiom_audit.py` from",
        "`data/result_registry.json`. It is deliberately excluded from `Ecdlp.lean`;",
        "CI elaborates it standalone and validates the output with",
        "`scripts/check_axioms.py`.",
        "-/",
        "",
    ]
    for name in names:
        lines.append(f"#print axioms {name}")
    return "\n".join(lines) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("ledger axiom audit is stale; run python3 scripts/gen_axiom_audit.py",
                  file=sys.stderr)
            return 1
        count = text.count("#print axioms ")
        print(f"ledger axiom audit up to date: {count} named declarations")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} — {text.count('#print axioms ')} declarations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
