#!/usr/bin/env python3
"""Generate the exhaustive #print axioms audits from the result registries.

Two generated audit files, one per trust lane (S0_TRUST_DESIGN.md §2.2):

  * Ecdlp/LedgerAxiomAudit.lean      <- data/result_registry.json
  * ResearchOS/LedgerAxiomAudit.lean <- data/researchos_result_registry.json

The Ecdlp output is byte-identical to what this script produced before the
ResearchOS lane existed (fixpoint/docs-sync stability). The ResearchOS audit
imports ONLY ResearchOS — the audit of the non-ECDLP lane must not elaborate
ECDLP code.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (registry path, output path, import lines, registry label in the docstring)
AUDITS = [
    (
        ROOT / "data" / "result_registry.json",
        ROOT / "Ecdlp" / "LedgerAxiomAudit.lean",
        ["import Ecdlp", "import ResearchOS"],
        "`data/result_registry.json`. It is deliberately excluded from `Ecdlp.lean`;",
    ),
    (
        ROOT / "data" / "researchos_result_registry.json",
        ROOT / "ResearchOS" / "LedgerAxiomAudit.lean",
        ["import ResearchOS"],
        "`data/researchos_result_registry.json`. It is deliberately excluded from "
        "`ResearchOS.lean`;",
    ),
]


def render(registry_path: Path, imports: list[str], registry_line: str) -> str:
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    names = registry.get("ledger_declarations", [])
    lines = [
        *imports,
        "",
        "/-!",
        "# Generated exhaustive ledger axiom audit",
        "",
        "Generated by `scripts/gen_axiom_audit.py` from",
        registry_line,
        "CI elaborates it standalone and validates the output with",
        "`scripts/check_axioms.py`.",
        "-/",
        "",
    ]
    for name in names:
        lines.append(f"#print axioms {name}")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    stale: list[str] = []
    total = 0
    for registry_path, out, imports, registry_line in AUDITS:
        text = render(registry_path, imports, registry_line)
        total += text.count("#print axioms ")
        if check:
            if not out.exists() or out.read_text(encoding="utf-8") != text:
                stale.append(out.relative_to(ROOT).as_posix())
            continue
        out.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {out.relative_to(ROOT)} — "
              f"{text.count('#print axioms ')} declarations")
    if check:
        if stale:
            print("ledger axiom audit is stale "
                  f"({', '.join(stale)}); run python3 scripts/gen_axiom_audit.py",
                  file=sys.stderr)
            return 1
        print(f"ledger axiom audit up to date: {total} named declarations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
