#!/usr/bin/env python3
"""Recursive Pratt primality certificate for secp256k1 p and n, with Lean emission.

Proves `m` prime via `Nat.lucas_primality`: a witness `a` of order m-1, plus a
recursive certificate for every prime q | m-1. This script builds, *verifies*, and
emits the Lean proof (one `pr_<m>` theorem per non-trivial prime, bottom-up).

Usage:  python3 scripts/pratt_certificate.py            # verify both
        python3 scripts/pratt_certificate.py lean p|n   # emit Lean to stdout
"""
import sys
from sympy import factorint, isprime

SMALL = 1 << 20  # below this, Lean's `norm_num` proves primality directly

p = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
n = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

def witness(m):
    facs = list(factorint(m - 1))
    for a in range(2, 500):
        if pow(a, m - 1, m) == 1 and all(pow(a, (m - 1) // q, m) != 1 for q in facs):
            return a
    raise RuntimeError(m)

def cert(m):
    assert isprime(m), m
    if m < SMALL:
        return {"m": m, "small": True}
    f = factorint(m - 1)
    return {"m": m, "a": witness(m), "factors": list(f.items()),
            "children": [cert(q) for q in f]}

def verify(c):
    m = c["m"]
    if c.get("small"):
        return isprime(m)
    a = c["a"]
    assert pow(a, m - 1, m) == 1
    prod = 1
    for q, e in c["factors"]:
        assert pow(a, (m - 1) // q, m) != 1
        prod *= q ** e
    assert prod == m - 1
    return all(verify(ch) for ch in c["children"])

def ref(q):
    return f"(show Nat.Prime {q} by norm_num)" if q < SMALL else f"pr_{q}"

def emit(c):
    """One `pr_<m>` theorem (assumes children already emitted)."""
    m, a, facs = c["m"], c["a"], c["factors"]
    _terms = [f"{q} ^ {e}" for q, e in facs]
    prod = _terms[-1]
    for _t in reversed(_terms[:-1]):
        prod = f"{_t} * ({prod})"
    L = [f"theorem pr_{m} : Nat.Prime {m} := by",
         f"  refine lucas_primality {m} ({a} : ZMod {m}) (by native_decide) ?_",
         f"  intro q hq hqd",
         f"  rw [show ({m} : ℕ) - 1 = {prod} by native_decide] at hqd"]
    def win(q, hyp, pad):
        L.append(f"{pad}rw [(Nat.prime_dvd_prime_iff_eq hq {ref(q)}).mp "
                 f"(hq.dvd_of_dvd_pow {hyp})]; native_decide")
    def go(rem, hyp, pad):
        if len(rem) == 1:
            win(rem[0][0], hyp, pad)
        else:
            L.append(f"{pad}rcases (Nat.Prime.dvd_mul hq).mp {hyp} with h | h")
            L.append(f"{pad}· " + f"rw [(Nat.prime_dvd_prime_iff_eq hq {ref(rem[0][0])}).mp "
                     f"(hq.dvd_of_dvd_pow h)]; native_decide")
            L.append(f"{pad}·")
            go(rem[1:], "h", pad + "  ")
    go(facs, "hqd", "  ")
    return "\n".join(L)

def collect(c, out, seen):
    if c.get("small") or c["m"] in seen:
        return
    for ch in c["children"]:
        collect(ch, out, seen)
    seen.add(c["m"])
    out.append(c)

def lean_file(which):
    m = p if which == "p" else n
    c = cert(m)
    assert verify(c)
    nodes = []
    collect(c, nodes, set())
    head = (f"import Mathlib\nimport Ecdlp.Secp256k1Verified\n\n"
            f"/-! # Machine-checked primality of secp256k1 `{which}` (Pratt certificate, "
            f"generated by `scripts/pratt_certificate.py`). Witness a={c['a']}, "
            f"{len(nodes)} recursive nodes. -/\n\nnamespace Ecdlp.Primality\n"
            f"open Nat\n")
    body = "\n\n".join(emit(x) for x in nodes)
    tail = (f"\n\n/-- secp256k1 {which} is prime (full Pratt certificate). -/\n"
            f"theorem secp256k1_{which}_prime : Nat.Prime Secp256k1.{which} := pr_{m}\n\n"
            f"instance : Fact (Nat.Prime Secp256k1.{which}) := ⟨secp256k1_{which}_prime⟩\n\n"
            f"end Ecdlp.Primality\n")
    return head + "\n" + body + tail

if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "lean":
        print(lean_file(sys.argv[2]))
    else:
        for nm, m in (("p", p), ("n", n)):
            c = cert(m); verify(c)
            print(f"{nm}: verified, a={c['a']}")
